Module Module2
    Public Function ZhToEn(StrZh As String, ZH As String(), EN As String()) As String
        Dim i As Int16
        For i = 0 To ZH.Count - 1
            If ZH(i) = StrZh Then
                Return EN(i)
                Exit Function
            End If
        Next
        Return ""
    End Function
    Public Function EnToZh(StrEn As String, ZH As String(), EN As String()) As String
        Dim i As Int16
        For i = 0 To EN.Count - 1
            If EN(i) = StrEn Then
                Return ZH(i)
                Exit Function
            End If
        Next
        Return ""
    End Function

    ' 触发器
    Public EnTriggers As String() = {
        "minecraft:bred_animals",
        "minecraft:brewed_potion",
        "minecraft:changed_dimension",
        "minecraft:construct_beacon",
        "minecraft:consume_item",
        "minecraft:cured_zombie_villager",
        "minecraft:effects_changed",
        "minecraft:enchanted_item",
        "minecraft:enter_block",
        "minecraft:entity_hurt_player",
        "minecraft:entity_killed_player",
        "minecraft:impossible",
        "minecraft:inventory_changed",
        "minecraft:item_durability_changed",
        "minecraft:levitation",
        "minecraft:location",
        "minecraft:nether_travel",
        "minecraft:placed_block",
        "minecraft:player_hurt_entity",
        "minecraft:player_killed_entity",
        "minecraft:recipe_unlocked",
        "minecraft:slept_in_bed",
        "minecraft:summoned_entity",
        "minecraft:tame_animal",
        "minecraft:tick",
        "minecraft:used_ender_eye",
        "minecraft:used_totem",
        "minecraft:villager_trade"
        }
    Public ZhTriggers As String() = {
        "繁殖动物",
        "从酿造台取出药水",
        "在两个维度间旅行",
        "更改信标结构",
        "损耗物品",
        "治愈僵尸村民",
        "获得/消除状态效果",
        "通过附魔台附魔物品",
        "进入方块",
        "实体伤害玩家",
        "实体杀死玩家",
        "不可能触发",
        "物品栏变化",
        "物品栏中任何物品以任何形式损耗",
        "获得漂浮状态效果",
        "玩家的位置",
        "进入下界，然后返回主世界",
        "放置方块",
        "伤害实体",
        "杀死实体",
        "解锁配方",
        "上床睡觉",
        "召唤实体",
        "驯服动物",
        "每个游戏刻",
        "使用末影之眼",
        "使用图腾",
        "与村民交易"
        }

    ' 药水ID
    Public EnPotions As String() = {
        "poison",
        "harming",
        "regeneration",
        "strength",
        "night_vision",
        "mundane",
        "luck",
        "fire_resistance",
        "water_breathing",
        "water",
        "healing",
        "thick",
        "awkward",
        "slowness",
        "weakness",
        "leaping",
        "swiftness",
        "invisibility",
        "strong_poison",
        "strong_harming",
        "strong_regeneration",
        "strong_strength",
        "strong_healing",
        "strong_leaping",
        "strong_swiftness",
        "long_poison",
        "long_regeneration",
        "long_strength",
        "long_night_vision",
        "long_fire_resistance",
        "long_water_breathing",
        "long_slowness",
        "long_weakness",
        "long_leaping",
        "long_swiftness",
        "long_invisibility"
        }
    Public ZhPotions As String() = {
        "中毒",
        "伤害",
        "再生",
        "力量",
        "夜视",
        "平凡的药水",
        "幸运",
        "抗火",
        "水下呼吸",
        "水瓶",
        "治疗",
        "浑浊的药水",
        "粗制的药水",
        "缓慢",
        "虚弱",
        "跳跃",
        "迅捷",
        "隐身",
        "II级中毒",
        "II级伤害",
        "II级再生",
        "II级力量",
        "II级治疗",
        "II级跳跃",
        "II级迅捷",
        "延长版中毒",
        "延长版再生",
        "延长版力量",
        "延长版夜视",
        "延长版抗火",
        "延长版水下呼吸",
        "延长版缓慢",
        "延长版虚弱",
        "延长版跳跃",
        "延长版迅捷",
        "延长版隐身"
        }

    ' 维度
    Public EnDimensions As String() = {
        "overworld",
        "the_nether",
        "the_end"
    }
    Public ZhDimensions As String() = {
        "主世界",
        "地狱",
        "末地"
    }

    ' 根进度图片
    Public EnImages As String() = {
        "bedrock",
        "bone_block_side",
        "bookshelf",
        "brewing_stand_base",
        "brick",
        "chorus_flower",
        "chorus_flower_dead",
        "chorus_plant",
        "clay",
        "coal_block",
        "coal_ore",
        "coarse_dirt",
        "cobblestone",
        "concrete_black",
        "concrete_blue",
        "concrete_brown",
        "concrete_cyan",
        "concrete_gray",
        "concrete_green",
        "concrete_light_blue",
        "concrete_lime",
        "concrete_magenta",
        "concrete_orange",
        "concrete_pink",
        "concrete_powder_black",
        "concrete_powder_blue",
        "concrete_powder_brown",
        "concrete_powder_cyan",
        "concrete_powder_gray",
        "concrete_powder_green",
        "concrete_powder_light_blue",
        "concrete_powder_lime",
        "concrete_powder_magenta",
        "concrete_powder_orange",
        "concrete_powder_pink",
        "concrete_powder_purple",
        "concrete_powder_red",
        "concrete_powder_silver",
        "concrete_powder_white",
        "concrete_powder_yellow",
        "concrete_purple",
        "concrete_red",
        "concrete_silver",
        "concrete_white",
        "concrete_yellow",
        "crafting_table_front",
        "crafting_table_side",
        "diamond_block",
        "diamond_ore",
        "dirt",
        "dirt_podzol_side",
        "dirt_podzol_top",
        "dragon_egg",
        "dropper_front_horizontal",
        "dropper_front_vertical",
        "emerald_block",
        "emerald_ore",
        "enchanting_table_bottom",
        "end_bricks",
        "end_stone",
        "farmland_dry",
        "farmland_wet",
        "frosted_ice_0",
        "frosted_ice_1",
        "frosted_ice_2",
        "frosted_ice_3",
        "furnace_front_off",
        "furnace_front_on",
        "furnace_side",
        "glass",
        "glass_black",
        "glass_blue",
        "glass_brown",
        "glass_cyan",
        "glass_gray",
        "glass_green",
        "glass_light_blue",
        "glass_lime",
        "glass_magenta",
        "glass_orange",
        "glass_pink",
        "glass_purple",
        "glass_red",
        "glass_silver",
        "glass_white",
        "glass_yellow",
        "glazed_terracotta_black",
        "glazed_terracotta_blue",
        "glazed_terracotta_brown",
        "glazed_terracotta_cyan",
        "glazed_terracotta_gray",
        "glazed_terracotta_green",
        "glazed_terracotta_light_blue",
        "glazed_terracotta_lime",
        "glazed_terracotta_magenta",
        "glazed_terracotta_orange",
        "glazed_terracotta_pink",
        "glazed_terracotta_purple",
        "glazed_terracotta_red",
        "glazed_terracotta_silver",
        "glazed_terracotta_white",
        "glazed_terracotta_yellow",
        "glowstone",
        "gold_block",
        "gold_ore",
        "grass_path_side",
        "grass_path_top",
        "grass_side",
        "grass_side_snowed",
        "grass_top",
        "gravel",
        "hardened_clay",
        "hardened_clay_stained_black",
        "hardened_clay_stained_blue",
        "hardened_clay_stained_brown",
        "hardened_clay_stained_cyan",
        "hardened_clay_stained_gray",
        "hardened_clay_stained_green",
        "hardened_clay_stained_light_blue",
        "hardened_clay_stained_lime",
        "hardened_clay_stained_magenta",
        "hardened_clay_stained_orange",
        "hardened_clay_stained_pink",
        "hardened_clay_stained_purple",
        "hardened_clay_stained_red",
        "hardened_clay_stained_silver",
        "hardened_clay_stained_white",
        "hardened_clay_stained_yellow",
        "hay_block_side",
        "hay_block_top",
        "hopper_inside",
        "hopper_outside",
        "ice",
        "ice_packed",
        "iron_block",
        "iron_ore",
        "jukebox_side",
        "lapis_block",
        "lapis_ore",
        "log_acacia",
        "log_acacia_top",
        "log_big_oak",
        "log_big_oak_top",
        "log_birch",
        "log_birch_top",
        "log_jungle",
        "log_jungle_top",
        "log_oak",
        "log_oak_top",
        "log_spruce",
        "log_spruce_top",
        "melon_side",
        "mob_spawner",
        "mushroom_block_inside",
        "mushroom_block_skin_brown",
        "mushroom_block_skin_red",
        "mushroom_block_skin_stem",
        "mycelium_side",
        "mycelium_top",
        "nether_brick",
        "nether_wart_block",
        "netherrack",
        "noteblock",
        "observer_front",
        "output.bat",
        "piston_side",
        "planks_acacia",
        "planks_big_oak",
        "planks_birch",
        "planks_jungle",
        "planks_oak",
        "planks_spruce",
        "prismarine_bricks",
        "prismarine_dark",
        "pumpkin_face_off",
        "pumpkin_face_on",
        "pumpkin_side",
        "pumpkin_top",
        "purpur_block",
        "purpur_pillar",
        "purpur_pillar_top",
        "quartz_block_bottom",
        "quartz_block_chiseled",
        "quartz_block_chiseled_top",
        "quartz_block_lines",
        "quartz_block_lines_top",
        "quartz_block_side",
        "quartz_block_top",
        "red_nether_brick",
        "red_sand",
        "red_sandstone_bottom",
        "red_sandstone_carved",
        "red_sandstone_normal",
        "red_sandstone_smooth",
        "red_sandstone_top",
        "redstone_block",
        "redstone_dust_overlay",
        "redstone_lamp_off",
        "redstone_lamp_on",
        "redstone_ore",
        "sand",
        "sandstone_bottom",
        "sandstone_carved",
        "sandstone_normal",
        "sandstone_smooth",
        "sandstone_top",
        "shulker_top_black",
        "shulker_top_blue",
        "shulker_top_brown",
        "shulker_top_cyan",
        "shulker_top_gray",
        "shulker_top_green",
        "shulker_top_light_blue",
        "shulker_top_lime",
        "shulker_top_magenta",
        "shulker_top_orange",
        "shulker_top_pink",
        "shulker_top_purple",
        "shulker_top_red",
        "shulker_top_silver",
        "shulker_top_white",
        "shulker_top_yellow",
        "slime",
        "snow",
        "soul_sand",
        "sponge",
        "sponge_wet",
        "stone",
        "stone_andesite",
        "stone_andesite_smooth",
        "stone_diorite",
        "stone_diorite_smooth",
        "stone_granite",
        "stone_granite_smooth",
        "stone_slab_side",
        "stone_slab_top",
        "stonebrick",
        "stonebrick_carved",
        "stonebrick_cracked",
        "stonebrick_mossy",
        "tnt_side",
        "wool_colored_black",
        "wool_colored_blue",
        "wool_colored_brown",
        "wool_colored_cyan",
        "wool_colored_gray",
        "wool_colored_green",
        "wool_colored_light_blue",
        "wool_colored_lime",
        "wool_colored_magenta",
        "wool_colored_orange",
        "wool_colored_pink",
        "wool_colored_purple",
        "wool_colored_red",
        "wool_colored_silver",
        "wool_colored_white",
        "wool_colored_yellow"
    }
    Public ZhImages As String() = {
        "基岩",
        "骨块",
        "书架",
        "brewing stand base",
        "brick",
        "chorus flower",
        "chorus flower dead",
        "chorus plant",
        "clay",
        "煤炭块",
        "煤矿",
        "coarse dirt",
        "cobblestone",
        "混凝土 black",
        "混凝土 blue",
        "混凝土 brown",
        "混凝土 cyan",
        "混凝土 gray",
        "混凝土 green",
        "混凝土 light blue",
        "混凝土 lime",
        "混凝土 magenta",
        "混凝土 orange",
        "混凝土 pink",
        "混凝土粉末 black",
        "混凝土粉末 blue",
        "混凝土粉末 brown",
        "混凝土粉末 cyan",
        "混凝土粉末 gray",
        "混凝土粉末 green",
        "混凝土粉末 light blue",
        "混凝土粉末 lime",
        "混凝土粉末 magenta",
        "混凝土粉末 orange",
        "混凝土粉末 pink",
        "混凝土粉末 purple",
        "混凝土粉末 red",
        "混凝土粉末 silver",
        "混凝土粉末 white",
        "混凝土粉末 yellow",
        "混凝土 purple",
        "混凝土 red",
        "混凝土 silver",
        "混凝土 white",
        "混凝土 yellow",
        "crafting table front",
        "crafting table side",
        "diamond block",
        "diamond ore",
        "dirt",
        "dirt podzol side",
        "dirt podzol top",
        "dragon egg",
        "dropper front horizontal",
        "dropper front vertical",
        "emerald block",
        "emerald ore",
        "enchanting table bottom",
        "end bricks",
        "end stone",
        "farmland dry",
        "farmland wet",
        "frosted ice 0",
        "frosted ice 1",
        "frosted ice 2",
        "frosted ice 3",
        "furnace front off",
        "furnace front on",
        "furnace side",
        "玻璃",
        "玻璃 black",
        "玻璃 blue",
        "玻璃 brown",
        "玻璃 cyan",
        "玻璃 gray",
        "玻璃 green",
        "玻璃 light blue",
        "玻璃 lime",
        "玻璃 magenta",
        "玻璃 orange",
        "玻璃 pink",
        "玻璃 purple",
        "玻璃 red",
        "玻璃 silver",
        "玻璃 white",
        "玻璃 yellow",
        "带釉陶瓦 black",
        "带釉陶瓦 blue",
        "带釉陶瓦 brown",
        "带釉陶瓦 cyan",
        "带釉陶瓦 gray",
        "带釉陶瓦 green",
        "带釉陶瓦 light blue",
        "带釉陶瓦 lime",
        "带釉陶瓦 magenta",
        "带釉陶瓦 orange",
        "带釉陶瓦 pink",
        "带釉陶瓦 purple",
        "带釉陶瓦 red",
        "带釉陶瓦 silver",
        "带釉陶瓦 white",
        "带釉陶瓦 yellow",
        "glowstone",
        "gold block",
        "gold ore",
        "grass path side",
        "grass path top",
        "grass side",
        "grass side snowed",
        "grass top",
        "gravel",
        "硬化粘土",
        "硬化染色粘土 black",
        "硬化染色粘土 blue",
        "硬化染色粘土 brown",
        "硬化染色粘土 cyan",
        "硬化染色粘土 gray",
        "硬化染色粘土 green",
        "硬化染色粘土 light blue",
        "硬化染色粘土 lime",
        "硬化染色粘土 magenta",
        "硬化染色粘土 orange",
        "硬化染色粘土 pink",
        "硬化染色粘土 purple",
        "硬化染色粘土 red",
        "硬化染色粘土 silver",
        "硬化染色粘土 white",
        "硬化染色粘土 yellow",
        "hay block side",
        "hay block top",
        "hopper inside",
        "hopper outside",
        "ice",
        "ice packed",
        "iron block",
        "iron ore",
        "jukebox side",
        "lapis block",
        "lapis ore",
        "log acacia",
        "log acacia top",
        "log big oak",
        "log big oak top",
        "log birch",
        "log birch top",
        "log jungle",
        "log jungle top",
        "log oak",
        "log oak top",
        "log spruce",
        "log spruce top",
        "melon side",
        "mob spawner",
        "mushroom block inside",
        "mushroom block skin brown",
        "mushroom block skin red",
        "mushroom block skin stem",
        "mycelium side",
        "mycelium top",
        "nether brick",
        "nether wart block",
        "netherrack",
        "noteblock",
        "observer front",
        "output.bat",
        "piston side",
        "planks acacia",
        "planks big oak",
        "planks birch",
        "planks jungle",
        "planks oak",
        "planks spruce",
        "prismarine bricks",
        "prismarine dark",
        "pumpkin face off",
        "pumpkin face on",
        "pumpkin side",
        "pumpkin top",
        "purpur block",
        "purpur pillar",
        "purpur pillar top",
        "quartz block bottom",
        "quartz block chiseled",
        "quartz block chiseled top",
        "quartz block lines",
        "quartz block lines top",
        "quartz block side",
        "quartz block top",
        "red nether brick",
        "red sand",
        "red sandstone bottom",
        "red sandstone carved",
        "red sandstone normal",
        "red sandstone smooth",
        "red sandstone top",
        "redstone block",
        "redstone dust overlay",
        "redstone lamp off",
        "redstone lamp on",
        "redstone ore",
        "sand",
        "sandstone bottom",
        "sandstone carved",
        "sandstone normal",
        "sandstone smooth",
        "sandstone top",
        "潜影盒 black",
        "潜影盒 blue",
        "潜影盒 brown",
        "潜影盒 cyan",
        "潜影盒 gray",
        "潜影盒 green",
        "潜影盒 light blue",
        "潜影盒 lime",
        "潜影盒 magenta",
        "潜影盒 orange",
        "潜影盒 pink",
        "潜影盒 purple",
        "潜影盒 red",
        "潜影盒 silver",
        "潜影盒 white",
        "潜影盒 yellow",
        "slime",
        "snow",
        "soul sand",
        "sponge",
        "sponge wet",
        "stone",
        "stone andesite",
        "stone andesite smooth",
        "stone diorite",
        "stone diorite smooth",
        "stone granite",
        "stone granite smooth",
        "stone slab side",
        "stone slab top",
        "stonebrick",
        "stonebrick carved",
        "stonebrick cracked",
        "stonebrick mossy",
        "tnt side",
        "染色羊毛 black",
        "染色羊毛 blue",
        "染色羊毛 brown",
        "染色羊毛 cyan",
        "染色羊毛 gray",
        "染色羊毛 green",
        "染色羊毛 light blue",
        "染色羊毛 lime",
        "染色羊毛 magenta",
        "染色羊毛 orange",
        "染色羊毛 pink",
        "染色羊毛 purple",
        "染色羊毛 red",
        "染色羊毛 silver",
        "染色羊毛 white",
        "染色羊毛 yellow"
    }

    ' 配方列表
    Public EnRecipes As String() = {
        ""
    }
    Public ZhRecipes As String() = {
        ""
    }

    ' 状态效果
    Public EnEffects As String() = {
"minecraft:speed",
"minecraft:slowness",
"minecraft:haste",
"minecraft:mining_fatigue",
"minecraft:strength",
"minecraft:instant_health",
"minecraft:instant_damage",
"minecraft:jump_boost",
"minecraft:nausea",
"minecraft:regeneration",
"minecraft:resistance",
"minecraft:fire_resistance",
"minecraft:water_breathing",
"minecraft:invisibility",
"minecraft:blindness",
"minecraft:night_vision",
"minecraft:hunger",
"minecraft:weakness",
"minecraft:poison",
"minecraft:wither",
"minecraft:health_boost",
"minecraft:absorption",
"minecraft:saturation",
"minecraft:glowing",
"minecraft:levitation",
"minecraft:luck",
"minecraft:unluck"
        }
    Public ZhEffects As String() = {
"速度",
"缓慢",
"急迫",
"挖掘疲劳",
"力量",
"瞬间治疗",
"瞬间伤害",
"跳跃提升",
"反胃",
"生命回复",
"抗性提升",
"防火",
"水下呼吸",
"隐身",
"失明",
"夜视",
"饥饿",
"虚弱",
"中毒",
"凋零",
"生命提升",
"伤害吸收",
"饱和",
"发光",
"飘浮",
"幸运",
"霉运"
        }

    ' 方块ID
    Public EnBlocks As String() = {
"minecraft:air",
"minecraft:stone",
"minecraft:grass",
"minecraft:dirt",
"minecraft:cobblestone",
"minecraft:planks",
"minecraft:sapling",
"minecraft:bedrock",
"minecraft:flowing_water",
"minecraft:water",
"minecraft:flowing_lava",
"minecraft:lava",
"minecraft:sand",
"minecraft:gravel",
"minecraft:gold_ore",
"minecraft:iron_ore",
"minecraft:coal_ore",
"minecraft:log",
"minecraft:leaves",
"minecraft:sponge",
"minecraft:glass",
"minecraft:lapis_ore",
"minecraft:lapis_block",
"minecraft:dispenser",
"minecraft:sandstone",
"minecraft:noteblock",
"minecraft:bed",
"minecraft:golden_rail",
"minecraft:detector_rail",
"minecraft:sticky_piston",
"minecraft:web",
"minecraft:tallgrass",
"minecraft:deadbush",
"minecraft:piston",
"minecraft:piston_head",
"minecraft:wool",
"minecraft:yellow_flower",
"minecraft:red_flower",
"minecraft:brown_mushroom",
"minecraft:red_mushroom",
"minecraft:gold_block",
"minecraft:iron_block",
"minecraft:double_stone_slab",
"minecraft:stone_slab",
"minecraft:brick_block",
"minecraft:tnt",
"minecraft:bookshelf",
"minecraft:mossy_cobblestone",
"minecraft:obsidian",
"minecraft:torch",
"minecraft:fire",
"minecraft:mob_spawner",
"minecraft:oak_stairs",
"minecraft:chest",
"minecraft:redstone_wire",
"minecraft:diamond_ore",
"minecraft:diamond_block",
"minecraft:crafting_table",
"minecraft:wheat",
"minecraft:farmland",
"minecraft:furnace",
"minecraft:lit_furnace",
"minecraft:standing_sign",
"minecraft:wooden_door",
"minecraft:ladder",
"minecraft:rail",
"minecraft:stone_stairs",
"minecraft:wall_sign",
"minecraft:lever",
"minecraft:stone_pressure_plate",
"minecraft:iron_door",
"minecraft:wooden_pressure_plate",
"minecraft:redstone_ore",
"minecraft:lit_redstone_ore",
"minecraft:unlit_redstone_torch",
"minecraft:redstone_torch",
"minecraft:stone_button",
"minecraft:snow_layer",
"minecraft:ice",
"minecraft:snow",
"minecraft:cactus",
"minecraft:clay",
"minecraft:reeds",
"minecraft:jukebox",
"minecraft:fence",
"minecraft:pumpkin",
"minecraft:netherrack",
"minecraft:soul_sand",
"minecraft:glowstone",
"minecraft:portal",
"minecraft:lit_pumpkin",
"minecraft:cake",
"minecraft:unpowered_repeater",
"minecraft:powered_repeater",
"minecraft:stained_glass",
"minecraft:trapdoor",
"minecraft:monster_egg",
"minecraft:stonebrick",
"minecraft:brown_mushroom_block",
"minecraft:red_mushroom_block",
"minecraft:iron_bars",
"minecraft:glass_pane",
"minecraft:melon_block",
"minecraft:pumpkin_stem",
"minecraft:melon_stem",
"minecraft:vine",
"minecraft:fence_gate",
"minecraft:brick_stairs",
"minecraft:stone_brick_stairs",
"minecraft:mycelium",
"minecraft:waterlily",
"minecraft:nether_brick",
"minecraft:nether_brick_fence",
"minecraft:nether_brick_stairs",
"minecraft:nether_wart",
"minecraft:enchanting_table",
"minecraft:brewing_stand",
"minecraft:cauldron",
"minecraft:end_portal",
"minecraft:end_portal_frame",
"minecraft:end_stone",
"minecraft:dragon_egg",
"minecraft:redstone_lamp",
"minecraft:lit_redstone_lamp",
"minecraft:double_wooden_slab",
"minecraft:wooden_slab",
"minecraft:cocoa",
"minecraft:sandstone_stairs",
"minecraft:emerald_ore",
"minecraft:ender_chest",
"minecraft:tripwire_hook",
"minecraft:tripwire",
"minecraft:emerald_block",
"minecraft:spruce_stairs",
"minecraft:birch_stairs",
"minecraft:jungle_stairs",
"minecraft:command_block",
"minecraft:beacon",
"minecraft:cobblestone_wall",
"minecraft:flower_pot",
"minecraft:carrots",
"minecraft:potatoes",
"minecraft:wooden_button",
"minecraft:skull",
"minecraft:anvil",
"minecraft:trapped_chest",
"minecraft:light_weighted_pressure_plate",
"minecraft:heavy_weighted_pressure_plate",
"minecraft:unpowered_comparator",
"minecraft:powered_comparator",
"minecraft:daylight_detector",
"minecraft:redstone_block",
"minecraft:quartz_ore",
"minecraft:hopper",
"minecraft:quartz_block",
"minecraft:quartz_stairs",
"minecraft:activator_rail",
"minecraft:dropper",
"minecraft:stained_hardened_clay",
"minecraft:stained_glass_pane",
"minecraft:leaves2",
"minecraft:log2",
"minecraft:acacia_stairs",
"minecraft:dark_oak_stairs",
"minecraft:slime",
"minecraft:barrier",
"minecraft:iron_trapdoor",
"minecraft:prismarine",
"minecraft:sea_lantern",
"minecraft:hay_block",
"minecraft:carpet",
"minecraft:terracotta",
"minecraft:coal_block",
"minecraft:packed_ice",
"minecraft:double_plant",
"minecraft:standing_banner",
"minecraft:wall_banner",
"minecraft:daylight_detector_inverted",
"minecraft:red_sandstone",
"minecraft:red_sandstone_stairs",
"minecraft:double_stone_slab2",
"minecraft:stone_slab2",
"minecraft:spruce_fence_gate",
"minecraft:birch_fence_gate",
"minecraft:jungle_fence_gate",
"minecraft:dark_oak_fence_gate",
"minecraft:acacia_fence_gate",
"minecraft:spruce_fence",
"minecraft:birch_fence",
"minecraft:jungle_fence",
"minecraft:dark_oak_fence",
"minecraft:acacia_fence",
"minecraft:spruce_door",
"minecraft:birch_door",
"minecraft:jungle_door",
"minecraft:acacia_door",
"minecraft:dark_oak_door",
"minecraft:end_rod",
"minecraft:chorus_plant",
"minecraft:chorus_flower",
"minecraft:purpur_block",
"minecraft:purpur_pillar",
"minecraft:purpur_stairs",
"minecraft:purpur_double_slab",
"minecraft:purpur_slab",
"minecraft:end_bricks",
"minecraft:beetroots",
"minecraft:grass_path",
"minecraft:end_gateway",
"minecraft:repeating_command_block",
"minecraft:chain_command_block",
"minecraft:frosted_ice",
"minecraft:magma",
"minecraft:nether_wart_block",
"minecraft:red_nether_brick",
"minecraft:bone_block",
"minecraft:structure_void",
"minecraft:observer",
"minecraft:white_shulker_box",
"minecraft:orange_shulker_box",
"minecraft:magenta_shulker_box",
"minecraft:light_blue_shulker_box",
"minecraft:yellow_shulker_box",
"minecraft:lime_shulker_box",
"minecraft:pink_shulker_box",
"minecraft:gray_shulker_box",
"minecraft:light_gray_shulker_box",
"minecraft:cyan_shulker_box",
"minecraft:purple_shulker_box",
"minecraft:blue_shulker_box",
"minecraft:brown_shulker_box",
"minecraft:green_shulker_box",
"minecraft:red_shulker_box",
"minecraft:black_shulker_box",
"minecraft:white_glazed_terracotta",
"minecraft:orange_glazed_terracotta",
"minecraft:magenta_glazed_terracotta",
"minecraft:light_blue_glazed_terracotta",
"minecraft:yellow_glazed_terracotta",
"minecraft:lime_glazed_terracotta",
"minecraft:pink_glazed_terracotta",
"minecraft:gray_glazed_terracotta",
"minecraft:light_gray_glazed_terracotta",
"minecraft:cyan_glazed_terracotta",
"minecraft:purple_glazed_terracotta",
"minecraft:blue_glazed_terracotta",
"minecraft:brown_glazed_terracotta",
"minecraft:green_glazed_terracotta",
"minecraft:red_glazed_terracotta",
"minecraft:black_glazed_terracotta",
"minecraft:concrete",
"minecraft:concrete_powder",
"minecraft:structure_block"
    }
    Public ZhBlocks As String() = {
"空气",
"石头",
"草方块",
"泥土",
"圆石",
"木板",
"树苗",
"基岩",
"水",
"静态水",
"熔岩",
"静态熔岩",
"沙子",
"沙砾",
"金矿石",
"铁矿石",
"煤矿石",
"木头",
"树叶",
"海绵",
"玻璃",
"青金石矿石",
"青金石块",
"发射器",
"砂岩",
"音符盒",
"床",
"充能铁轨",
"探测铁轨",
"粘性活塞",
"蜘蛛网",
"草丛",
"枯死的灌木",
"活塞",
"活塞臂",
"羊毛",
"蒲公英",
"虞美人",
"棕色蘑菇",
"红色蘑菇",
"金块",
"铁块",
"双石台阶",
"石台阶",
"砖块",
"TNT",
"书架",
"苔石",
"黑曜石",
"火把",
"火",
"刷怪箱",
"橡木楼梯",
"箱子",
"红石线",
"钻石矿石",
"钻石块",
"工作台",
"小麦",
"耕地",
"熔炉",
"燃烧的熔炉",
"站立的告示牌",
"橡木门",
"梯子",
"铁轨",
"圆石楼梯",
"墙上的告示牌",
"拉杆",
"石质压力板",
"铁门",
"木质压力板",
"红石矿石",
"发光的红石矿石",
"红石火把（未开启）",
"红石火把（已开启）",
"石质按钮",
"雪块",
"冰",
"雪块",
"仙人掌",
"粘土",
"甘蔗",
"唱片机",
"橡木栅栏",
"南瓜",
"地狱岩",
"灵魂沙",
"荧石",
"下界传送门",
"南瓜灯",
"蛋糕",
"红石中继器（未开启）",
"红石中继器（已开启）",
"染色玻璃",
"活板门",
"怪物蛋",
"石砖",
"棕色巨型蘑菇",
"红色巨型蘑菇",
"铁栏杆",
"玻璃板",
"西瓜片",
"南瓜梗",
"西瓜梗",
"藤蔓",
"栅栏门",
"砖块楼梯",
"石砖楼梯",
"菌丝",
"睡莲",
"地狱砖块",
"地狱砖栅栏",
"地狱砖楼梯",
"地狱疣",
"附魔台",
"酿造台",
"炼药锅",
"末地传送门方块",
"末地传送门框架",
"末地石",
"龙蛋",
"红石灯（未开启）",
"红石灯（已开启）",
"双木台阶",
"木台阶",
"可可果",
"砂岩楼梯",
"绿宝石矿石",
"末影箱",
"绊线钩",
"绊线",
"绿宝石块",
"云杉楼梯",
"桦木楼梯",
"丛林楼梯",
"命令方块",
"信标",
"圆石墙",
"花盆",
"胡萝卜",
"马铃薯",
"木质按钮",
"生物头颅",
"铁砧",
"陷阱箱",
"测重压力板（轻质）",
"测重压力板（重质）",
"红石比较器",
"红石比较器（已弃用）",
"阳光传感器",
"红石块",
"下界石英矿石",
"漏斗",
"石英块",
"石英楼梯",
"激活铁轨",
"投掷器",
"染色陶瓦",
"染色玻璃板",
"树叶（金合欢/深色橡木）",
"木头（金合欢/深色橡木）",
"金合欢楼梯",
"深色橡木楼梯",
"粘液块",
"屏障",
"铁活板门",
"海晶石",
"海晶灯",
"干草块",
"地毯",
"陶瓦",
"煤炭块",
"浮冰",
"大型花",
"站立的旗帜",
"墙上的旗帜",
"反向阳光传感器",
"红砂岩",
"红砂岩楼梯",
"双红砂岩台阶",
"红砂岩台阶",
"云杉木栅栏门",
"白桦木栅栏门",
"丛林木栅栏门",
"深色橡木栅栏门",
"金合欢栅栏门",
"云杉木栅栏",
"白桦木栅栏",
"丛林木栅栏",
"深色橡木栅栏",
"金合欢栅栏",
"云杉木门",
"白桦木门",
"丛林木门",
"金合欢木门",
"深色橡木门",
"末地烛",
"紫颂植物",
"紫颂花",
"紫珀块",
"竖纹紫珀块",
"紫珀块楼梯",
"双紫珀台阶",
"紫珀块台阶",
"末地石砖",
"甜菜种子",
"草径",
"末地折跃门方块",
"循环型命令方块",
"连锁型命令方块",
"霜冰",
"岩浆块",
"地狱疣块",
"红色地狱砖",
"骨块",
"结构空位",
"侦测器",
"白色潜影盒",
"橙色潜影盒",
"品红色潜影盒",
"淡蓝色潜影盒",
"黄色潜影盒",
"黄绿色潜影盒",
"粉红色潜影盒",
"灰色潜影盒",
"淡灰色潜影盒",
"青色潜影盒",
"紫色潜影盒",
"蓝色潜影盒",
"棕色潜影盒",
"绿色潜影盒",
"红色潜影盒",
"黑色潜影盒",
"白色带釉陶瓦",
"橙色带釉陶瓦",
"品红色带釉陶瓦",
"淡蓝色带釉陶瓦",
"黄色带釉陶瓦",
"黄绿色带釉陶瓦",
"粉红色带釉陶瓦",
"灰色带釉陶瓦",
"淡灰色带釉陶瓦",
"青色带釉陶瓦",
"紫色带釉陶瓦",
"蓝色带釉陶瓦",
"棕色带釉陶瓦",
"绿色带釉陶瓦",
"红色带釉陶瓦",
"黑色带釉陶瓦",
"混凝土",
"混凝土粉末",
"结构方块"
    }
End Module
