Module Module2
    ' 函数
    Public Function ZhToEn(StrZh As String, ZH As String(), EN As String()) As String
        Dim i As Int16
        For i = 0 To ZH.Count - 1
            If ZH(i) = StrZh Then
                Return EN(i)
                Exit Function
            End If
        Next
        Return StrZh
    End Function
    Public Function EnToZh(StrEn As String, ZH As String(), EN As String()) As String
        Dim i As Int16
        For i = 0 To EN.Count - 1
            If EN(i) = StrEn Then
                Return ZH(i)
                Exit Function
            End If
        Next
        Return StrEn
    End Function

    ' 触发器
    ' 来自 minecraft wiki
    Public EnTriggers As String() = {
"minecraft:bred_animals",
"minecraft:brewed_potion",
"minecraft:changed_dimension",
"minecraft:construct_beacon",
"minecraft:consume_item",
"minecraft:cured_zombie_villager",
"minecraft:effects_changed",
"minecraft:enchanted_item",
"minecraft:enter_block",
"minecraft:entity_hurt_player",
"minecraft:entity_killed_player",
"minecraft:impossible",
"minecraft:inventory_changed",
"minecraft:item_durability_changed",
"minecraft:levitation",
"minecraft:location",
"minecraft:nether_travel",
"minecraft:placed_block",
"minecraft:player_hurt_entity",
"minecraft:player_killed_entity",
"minecraft:recipe_unlocked",
"minecraft:slept_in_bed",
"minecraft:summoned_entity",
"minecraft:tame_animal",
"minecraft:tick",
"minecraft:used_ender_eye",
"minecraft:used_totem",
"minecraft:villager_trade"
    }
    Public ZhTriggers As String() = {
"繁殖动物",
"从酿造台取出药水",
"在两个维度间旅行",
"更改信标结构",
"损耗物品",
"治愈僵尸村民",
"获得/消除状态效果",
"通过附魔台附魔物品",
"进入方块",
"实体伤害玩家",
"实体杀死玩家",
"不可能触发",
"物品栏变化",
"物品栏中任何物品以任何形式损耗",
"获得漂浮状态效果",
"玩家的位置",
"进入下界，然后返回主世界",
"放置方块",
"伤害实体",
"杀死实体",
"解锁配方",
"上床睡觉",
"召唤实体",
"驯服动物",
"每个游戏刻",
"使用末影之眼",
"使用图腾",
"与村民交易"
    }

    ' 药水ID
    ' 来自 minecraft wiki 列表
    Public EnPotions As String() = {
"poison",
"harming",
"regeneration",
"strength",
"night_vision",
"mundane",
"luck",
"fire_resistance",
"water_breathing",
"water",
"healing",
"thick",
"awkward",
"slowness",
"weakness",
"leaping",
"swiftness",
"invisibility",
"strong_poison",
"strong_harming",
"strong_regeneration",
"strong_strength",
"strong_healing",
"strong_leaping",
"strong_swiftness",
"long_poison",
"long_regeneration",
"long_strength",
"long_night_vision",
"long_fire_resistance",
"long_water_breathing",
"long_slowness",
"long_weakness",
"long_leaping",
"long_swiftness",
"long_invisibility"
    }
    Public ZhPotions As String() = {
"中毒",
"伤害",
"再生",
"力量",
"夜视",
"平凡的药水",
"幸运",
"抗火",
"水下呼吸",
"水瓶",
"治疗",
"浑浊的药水",
"粗制的药水",
"缓慢",
"虚弱",
"跳跃",
"迅捷",
"隐身",
"II级中毒",
"II级伤害",
"II级再生",
"II级力量",
"II级治疗",
"II级跳跃",
"II级迅捷",
"延长版中毒",
"延长版再生",
"延长版力量",
"延长版夜视",
"延长版抗火",
"延长版水下呼吸",
"延长版缓慢",
"延长版虚弱",
"延长版跳跃",
"延长版迅捷",
"延长版隐身"
    }

    ' 维度
    ' 来自 minecraft wiki
    Public EnDimensions As String() = {
"overworld",
"the_nether",
"the_end"
    }
    Public ZhDimensions As String() = {
"主世界",
"地狱",
"末地"
    }

    ' 根进度图片
    ' 来自 bat 文件输出文件列表
    Public EnBackgrounds As String() = {
"bedrock",
"bone_block_side",
"bookshelf",
"brewing_stand_base",
"brick",
"chorus_flower",
"chorus_flower_dead",
"chorus_plant",
"clay",
"coal_block",
"coal_ore",
"coarse_dirt",
"cobblestone",
"concrete_black",
"concrete_blue",
"concrete_brown",
"concrete_cyan",
"concrete_gray",
"concrete_green",
"concrete_light_blue",
"concrete_lime",
"concrete_magenta",
"concrete_orange",
"concrete_pink",
"concrete_powder_black",
"concrete_powder_blue",
"concrete_powder_brown",
"concrete_powder_cyan",
"concrete_powder_gray",
"concrete_powder_green",
"concrete_powder_light_blue",
"concrete_powder_lime",
"concrete_powder_magenta",
"concrete_powder_orange",
"concrete_powder_pink",
"concrete_powder_purple",
"concrete_powder_red",
"concrete_powder_silver",
"concrete_powder_white",
"concrete_powder_yellow",
"concrete_purple",
"concrete_red",
"concrete_silver",
"concrete_white",
"concrete_yellow",
"crafting_table_front",
"crafting_table_side",
"diamond_block",
"diamond_ore",
"dirt",
"dirt_podzol_side",
"dirt_podzol_top",
"dragon_egg",
"dropper_front_horizontal",
"dropper_front_vertical",
"emerald_block",
"emerald_ore",
"enchanting_table_bottom",
"end_bricks",
"end_stone",
"farmland_dry",
"farmland_wet",
"frosted_ice_0",
"frosted_ice_1",
"frosted_ice_2",
"frosted_ice_3",
"furnace_front_off",
"furnace_front_on",
"furnace_side",
"glass",
"glass_black",
"glass_blue",
"glass_brown",
"glass_cyan",
"glass_gray",
"glass_green",
"glass_light_blue",
"glass_lime",
"glass_magenta",
"glass_orange",
"glass_pink",
"glass_purple",
"glass_red",
"glass_silver",
"glass_white",
"glass_yellow",
"glazed_terracotta_black",
"glazed_terracotta_blue",
"glazed_terracotta_brown",
"glazed_terracotta_cyan",
"glazed_terracotta_gray",
"glazed_terracotta_green",
"glazed_terracotta_light_blue",
"glazed_terracotta_lime",
"glazed_terracotta_magenta",
"glazed_terracotta_orange",
"glazed_terracotta_pink",
"glazed_terracotta_purple",
"glazed_terracotta_red",
"glazed_terracotta_silver",
"glazed_terracotta_white",
"glazed_terracotta_yellow",
"glowstone",
"gold_block",
"gold_ore",
"grass_path_side",
"grass_path_top",
"grass_side",
"grass_side_snowed",
"grass_top",
"gravel",
"hardened_clay",
"hardened_clay_stained_black",
"hardened_clay_stained_blue",
"hardened_clay_stained_brown",
"hardened_clay_stained_cyan",
"hardened_clay_stained_gray",
"hardened_clay_stained_green",
"hardened_clay_stained_light_blue",
"hardened_clay_stained_lime",
"hardened_clay_stained_magenta",
"hardened_clay_stained_orange",
"hardened_clay_stained_pink",
"hardened_clay_stained_purple",
"hardened_clay_stained_red",
"hardened_clay_stained_silver",
"hardened_clay_stained_white",
"hardened_clay_stained_yellow",
"hay_block_side",
"hay_block_top",
"hopper_inside",
"hopper_outside",
"ice",
"ice_packed",
"iron_block",
"iron_ore",
"jukebox_side",
"lapis_block",
"lapis_ore",
"log_acacia",
"log_acacia_top",
"log_big_oak",
"log_big_oak_top",
"log_birch",
"log_birch_top",
"log_jungle",
"log_jungle_top",
"log_oak",
"log_oak_top",
"log_spruce",
"log_spruce_top",
"melon_side",
"mob_spawner",
"mushroom_block_inside",
"mushroom_block_skin_brown",
"mushroom_block_skin_red",
"mushroom_block_skin_stem",
"mycelium_side",
"mycelium_top",
"nether_brick",
"nether_wart_block",
"netherrack",
"noteblock",
"observer_front",
"piston_side",
"planks_acacia",
"planks_big_oak",
"planks_birch",
"planks_jungle",
"planks_oak",
"planks_spruce",
"prismarine_bricks",
"prismarine_dark",
"pumpkin_face_off",
"pumpkin_face_on",
"pumpkin_side",
"pumpkin_top",
"purpur_block",
"purpur_pillar",
"purpur_pillar_top",
"quartz_block_bottom",
"quartz_block_chiseled",
"quartz_block_chiseled_top",
"quartz_block_lines",
"quartz_block_lines_top",
"quartz_block_side",
"quartz_block_top",
"red_nether_brick",
"red_sand",
"red_sandstone_bottom",
"red_sandstone_carved",
"red_sandstone_normal",
"red_sandstone_smooth",
"red_sandstone_top",
"redstone_block",
"redstone_dust_overlay",
"redstone_lamp_off",
"redstone_lamp_on",
"redstone_ore",
"sand",
"sandstone_bottom",
"sandstone_carved",
"sandstone_normal",
"sandstone_smooth",
"sandstone_top",
"shulker_top_black",
"shulker_top_blue",
"shulker_top_brown",
"shulker_top_cyan",
"shulker_top_gray",
"shulker_top_green",
"shulker_top_light_blue",
"shulker_top_lime",
"shulker_top_magenta",
"shulker_top_orange",
"shulker_top_pink",
"shulker_top_purple",
"shulker_top_red",
"shulker_top_silver",
"shulker_top_white",
"shulker_top_yellow",
"slime",
"snow",
"soul_sand",
"sponge",
"sponge_wet",
"stone",
"stone_andesite",
"stone_andesite_smooth",
"stone_diorite",
"stone_diorite_smooth",
"stone_granite",
"stone_granite_smooth",
"stone_slab_side",
"stone_slab_top",
"stonebrick",
"stonebrick_carved",
"stonebrick_cracked",
"stonebrick_mossy",
"tnt_side",
"wool_colored_black",
"wool_colored_blue",
"wool_colored_brown",
"wool_colored_cyan",
"wool_colored_gray",
"wool_colored_green",
"wool_colored_light_blue",
"wool_colored_lime",
"wool_colored_magenta",
"wool_colored_orange",
"wool_colored_pink",
"wool_colored_purple",
"wool_colored_red",
"wool_colored_silver",
"wool_colored_white",
"wool_colored_yellow"
    }
    Public ZhBackgrounds As String() = {
"基岩",
"骨块",
"书架",
"brewing stand base",
"brick",
"chorus flower",
"chorus flower dead",
"chorus plant",
"clay",
"煤炭块",
"煤矿",
"coarse dirt",
"cobblestone",
"混凝土 black",
"混凝土 blue",
"混凝土 brown",
"混凝土 cyan",
"混凝土 gray",
"混凝土 green",
"混凝土 light blue",
"混凝土 lime",
"混凝土 magenta",
"混凝土 orange",
"混凝土 pink",
"混凝土粉末 black",
"混凝土粉末 blue",
"混凝土粉末 brown",
"混凝土粉末 cyan",
"混凝土粉末 gray",
"混凝土粉末 green",
"混凝土粉末 light blue",
"混凝土粉末 lime",
"混凝土粉末 magenta",
"混凝土粉末 orange",
"混凝土粉末 pink",
"混凝土粉末 purple",
"混凝土粉末 red",
"混凝土粉末 silver",
"混凝土粉末 white",
"混凝土粉末 yellow",
"混凝土 purple",
"混凝土 red",
"混凝土 silver",
"混凝土 white",
"混凝土 yellow",
"crafting table front",
"crafting table side",
"diamond block",
"diamond ore",
"dirt",
"dirt podzol side",
"dirt podzol top",
"dragon egg",
"dropper front horizontal",
"dropper front vertical",
"emerald block",
"emerald ore",
"enchanting table bottom",
"end bricks",
"end stone",
"farmland dry",
"farmland wet",
"frosted ice 0",
"frosted ice 1",
"frosted ice 2",
"frosted ice 3",
"furnace front off",
"furnace front on",
"furnace side",
"玻璃",
"玻璃 black",
"玻璃 blue",
"玻璃 brown",
"玻璃 cyan",
"玻璃 gray",
"玻璃 green",
"玻璃 light blue",
"玻璃 lime",
"玻璃 magenta",
"玻璃 orange",
"玻璃 pink",
"玻璃 purple",
"玻璃 red",
"玻璃 silver",
"玻璃 white",
"玻璃 yellow",
"带釉陶瓦 black",
"带釉陶瓦 blue",
"带釉陶瓦 brown",
"带釉陶瓦 cyan",
"带釉陶瓦 gray",
"带釉陶瓦 green",
"带釉陶瓦 light blue",
"带釉陶瓦 lime",
"带釉陶瓦 magenta",
"带釉陶瓦 orange",
"带釉陶瓦 pink",
"带釉陶瓦 purple",
"带釉陶瓦 red",
"带釉陶瓦 silver",
"带釉陶瓦 white",
"带釉陶瓦 yellow",
"glowstone",
"gold block",
"gold ore",
"grass path side",
"grass path top",
"grass side",
"grass side snowed",
"grass top",
"gravel",
"硬化粘土",
"硬化染色粘土 black",
"硬化染色粘土 blue",
"硬化染色粘土 brown",
"硬化染色粘土 cyan",
"硬化染色粘土 gray",
"硬化染色粘土 green",
"硬化染色粘土 light blue",
"硬化染色粘土 lime",
"硬化染色粘土 magenta",
"硬化染色粘土 orange",
"硬化染色粘土 pink",
"硬化染色粘土 purple",
"硬化染色粘土 red",
"硬化染色粘土 silver",
"硬化染色粘土 white",
"硬化染色粘土 yellow",
"hay block side",
"hay block top",
"hopper inside",
"hopper outside",
"ice",
"ice packed",
"iron block",
"iron ore",
"jukebox side",
"lapis block",
"lapis ore",
"log acacia",
"log acacia top",
"log big oak",
"log big oak top",
"log birch",
"log birch top",
"log jungle",
"log jungle top",
"log oak",
"log oak top",
"log spruce",
"log spruce top",
"melon side",
"mob spawner",
"mushroom block inside",
"mushroom block skin brown",
"mushroom block skin red",
"mushroom block skin stem",
"mycelium side",
"mycelium top",
"nether brick",
"nether wart block",
"netherrack",
"noteblock",
"observer front",
"piston side",
"planks acacia",
"planks big oak",
"planks birch",
"planks jungle",
"planks oak",
"planks spruce",
"prismarine bricks",
"prismarine dark",
"pumpkin face off",
"pumpkin face on",
"pumpkin side",
"pumpkin top",
"purpur block",
"purpur pillar",
"purpur pillar top",
"quartz block bottom",
"quartz block chiseled",
"quartz block chiseled top",
"quartz block lines",
"quartz block lines top",
"quartz block side",
"quartz block top",
"red nether brick",
"red sand",
"red sandstone bottom",
"red sandstone carved",
"red sandstone normal",
"red sandstone smooth",
"red sandstone top",
"redstone block",
"redstone dust overlay",
"redstone lamp off",
"redstone lamp on",
"redstone ore",
"sand",
"sandstone bottom",
"sandstone carved",
"sandstone normal",
"sandstone smooth",
"sandstone top",
"潜影盒 black",
"潜影盒 blue",
"潜影盒 brown",
"潜影盒 cyan",
"潜影盒 gray",
"潜影盒 green",
"潜影盒 light blue",
"潜影盒 lime",
"潜影盒 magenta",
"潜影盒 orange",
"潜影盒 pink",
"潜影盒 purple",
"潜影盒 red",
"潜影盒 silver",
"潜影盒 white",
"潜影盒 yellow",
"slime",
"snow",
"soul sand",
"sponge",
"sponge wet",
"stone",
"stone andesite",
"stone andesite smooth",
"stone diorite",
"stone diorite smooth",
"stone granite",
"stone granite smooth",
"stone slab side",
"stone slab top",
"stonebrick",
"stonebrick carved",
"stonebrick cracked",
"stonebrick mossy",
"tnt side",
"染色羊毛 black",
"染色羊毛 blue",
"染色羊毛 brown",
"染色羊毛 cyan",
"染色羊毛 gray",
"染色羊毛 green",
"染色羊毛 light blue",
"染色羊毛 lime",
"染色羊毛 magenta",
"染色羊毛 orange",
"染色羊毛 pink",
"染色羊毛 purple",
"染色羊毛 red",
"染色羊毛 silver",
"染色羊毛 white",
"染色羊毛 yellow"
    }

    ' 状态效果
    ' 来自 minecraft wiki 列表
    Public EnEffects As String() = {
"minecraft:speed",
"minecraft:slowness",
"minecraft:haste",
"minecraft:mining_fatigue",
"minecraft:strength",
"minecraft:instant_health",
"minecraft:instant_damage",
"minecraft:jump_boost",
"minecraft:nausea",
"minecraft:regeneration",
"minecraft:resistance",
"minecraft:fire_resistance",
"minecraft:water_breathing",
"minecraft:invisibility",
"minecraft:blindness",
"minecraft:night_vision",
"minecraft:hunger",
"minecraft:weakness",
"minecraft:poison",
"minecraft:wither",
"minecraft:health_boost",
"minecraft:absorption",
"minecraft:saturation",
"minecraft:glowing",
"minecraft:levitation",
"minecraft:luck",
"minecraft:unluck"
        }
    Public ZhEffects As String() = {
"速度",
"缓慢",
"急迫",
"挖掘疲劳",
"力量",
"瞬间治疗",
"瞬间伤害",
"跳跃提升",
"反胃",
"生命回复",
"抗性提升",
"防火",
"水下呼吸",
"隐身",
"失明",
"夜视",
"饥饿",
"虚弱",
"中毒",
"凋零",
"生命提升",
"伤害吸收",
"饱和",
"发光",
"飘浮",
"幸运",
"霉运"
        }

    ' 方块ID
    ' 来自 minecraft wiki 列表
    Public EnBlocks As String() = {
"minecraft:air",
"minecraft:stone",
"minecraft:grass",
"minecraft:dirt",
"minecraft:cobblestone",
"minecraft:planks",
"minecraft:sapling",
"minecraft:bedrock",
"minecraft:flowing_water",
"minecraft:water",
"minecraft:flowing_lava",
"minecraft:lava",
"minecraft:sand",
"minecraft:gravel",
"minecraft:gold_ore",
"minecraft:iron_ore",
"minecraft:coal_ore",
"minecraft:log",
"minecraft:leaves",
"minecraft:sponge",
"minecraft:glass",
"minecraft:lapis_ore",
"minecraft:lapis_block",
"minecraft:dispenser",
"minecraft:sandstone",
"minecraft:noteblock",
"minecraft:bed",
"minecraft:golden_rail",
"minecraft:detector_rail",
"minecraft:sticky_piston",
"minecraft:web",
"minecraft:tallgrass",
"minecraft:deadbush",
"minecraft:piston",
"minecraft:piston_head",
"minecraft:wool",
"minecraft:yellow_flower",
"minecraft:red_flower",
"minecraft:brown_mushroom",
"minecraft:red_mushroom",
"minecraft:gold_block",
"minecraft:iron_block",
"minecraft:double_stone_slab",
"minecraft:stone_slab",
"minecraft:brick_block",
"minecraft:tnt",
"minecraft:bookshelf",
"minecraft:mossy_cobblestone",
"minecraft:obsidian",
"minecraft:torch",
"minecraft:fire",
"minecraft:mob_spawner",
"minecraft:oak_stairs",
"minecraft:chest",
"minecraft:redstone_wire",
"minecraft:diamond_ore",
"minecraft:diamond_block",
"minecraft:crafting_table",
"minecraft:wheat",
"minecraft:farmland",
"minecraft:furnace",
"minecraft:lit_furnace",
"minecraft:standing_sign",
"minecraft:wooden_door",
"minecraft:ladder",
"minecraft:rail",
"minecraft:stone_stairs",
"minecraft:wall_sign",
"minecraft:lever",
"minecraft:stone_pressure_plate",
"minecraft:iron_door",
"minecraft:wooden_pressure_plate",
"minecraft:redstone_ore",
"minecraft:lit_redstone_ore",
"minecraft:unlit_redstone_torch",
"minecraft:redstone_torch",
"minecraft:stone_button",
"minecraft:snow_layer",
"minecraft:ice",
"minecraft:snow",
"minecraft:cactus",
"minecraft:clay",
"minecraft:reeds",
"minecraft:jukebox",
"minecraft:fence",
"minecraft:pumpkin",
"minecraft:netherrack",
"minecraft:soul_sand",
"minecraft:glowstone",
"minecraft:portal",
"minecraft:lit_pumpkin",
"minecraft:cake",
"minecraft:unpowered_repeater",
"minecraft:powered_repeater",
"minecraft:stained_glass",
"minecraft:trapdoor",
"minecraft:monster_egg",
"minecraft:stonebrick",
"minecraft:brown_mushroom_block",
"minecraft:red_mushroom_block",
"minecraft:iron_bars",
"minecraft:glass_pane",
"minecraft:melon_block",
"minecraft:pumpkin_stem",
"minecraft:melon_stem",
"minecraft:vine",
"minecraft:fence_gate",
"minecraft:brick_stairs",
"minecraft:stone_brick_stairs",
"minecraft:mycelium",
"minecraft:waterlily",
"minecraft:nether_brick",
"minecraft:nether_brick_fence",
"minecraft:nether_brick_stairs",
"minecraft:nether_wart",
"minecraft:enchanting_table",
"minecraft:brewing_stand",
"minecraft:cauldron",
"minecraft:end_portal",
"minecraft:end_portal_frame",
"minecraft:end_stone",
"minecraft:dragon_egg",
"minecraft:redstone_lamp",
"minecraft:lit_redstone_lamp",
"minecraft:double_wooden_slab",
"minecraft:wooden_slab",
"minecraft:cocoa",
"minecraft:sandstone_stairs",
"minecraft:emerald_ore",
"minecraft:ender_chest",
"minecraft:tripwire_hook",
"minecraft:tripwire",
"minecraft:emerald_block",
"minecraft:spruce_stairs",
"minecraft:birch_stairs",
"minecraft:jungle_stairs",
"minecraft:command_block",
"minecraft:beacon",
"minecraft:cobblestone_wall",
"minecraft:flower_pot",
"minecraft:carrots",
"minecraft:potatoes",
"minecraft:wooden_button",
"minecraft:skull",
"minecraft:anvil",
"minecraft:trapped_chest",
"minecraft:light_weighted_pressure_plate",
"minecraft:heavy_weighted_pressure_plate",
"minecraft:unpowered_comparator",
"minecraft:powered_comparator",
"minecraft:daylight_detector",
"minecraft:redstone_block",
"minecraft:quartz_ore",
"minecraft:hopper",
"minecraft:quartz_block",
"minecraft:quartz_stairs",
"minecraft:activator_rail",
"minecraft:dropper",
"minecraft:stained_hardened_clay",
"minecraft:stained_glass_pane",
"minecraft:leaves2",
"minecraft:log2",
"minecraft:acacia_stairs",
"minecraft:dark_oak_stairs",
"minecraft:slime",
"minecraft:barrier",
"minecraft:iron_trapdoor",
"minecraft:prismarine",
"minecraft:sea_lantern",
"minecraft:hay_block",
"minecraft:carpet",
"minecraft:terracotta",
"minecraft:coal_block",
"minecraft:packed_ice",
"minecraft:double_plant",
"minecraft:standing_banner",
"minecraft:wall_banner",
"minecraft:daylight_detector_inverted",
"minecraft:red_sandstone",
"minecraft:red_sandstone_stairs",
"minecraft:double_stone_slab2",
"minecraft:stone_slab2",
"minecraft:spruce_fence_gate",
"minecraft:birch_fence_gate",
"minecraft:jungle_fence_gate",
"minecraft:dark_oak_fence_gate",
"minecraft:acacia_fence_gate",
"minecraft:spruce_fence",
"minecraft:birch_fence",
"minecraft:jungle_fence",
"minecraft:dark_oak_fence",
"minecraft:acacia_fence",
"minecraft:spruce_door",
"minecraft:birch_door",
"minecraft:jungle_door",
"minecraft:acacia_door",
"minecraft:dark_oak_door",
"minecraft:end_rod",
"minecraft:chorus_plant",
"minecraft:chorus_flower",
"minecraft:purpur_block",
"minecraft:purpur_pillar",
"minecraft:purpur_stairs",
"minecraft:purpur_double_slab",
"minecraft:purpur_slab",
"minecraft:end_bricks",
"minecraft:beetroots",
"minecraft:grass_path",
"minecraft:end_gateway",
"minecraft:repeating_command_block",
"minecraft:chain_command_block",
"minecraft:frosted_ice",
"minecraft:magma",
"minecraft:nether_wart_block",
"minecraft:red_nether_brick",
"minecraft:bone_block",
"minecraft:structure_void",
"minecraft:observer",
"minecraft:white_shulker_box",
"minecraft:orange_shulker_box",
"minecraft:magenta_shulker_box",
"minecraft:light_blue_shulker_box",
"minecraft:yellow_shulker_box",
"minecraft:lime_shulker_box",
"minecraft:pink_shulker_box",
"minecraft:gray_shulker_box",
"minecraft:light_gray_shulker_box",
"minecraft:cyan_shulker_box",
"minecraft:purple_shulker_box",
"minecraft:blue_shulker_box",
"minecraft:brown_shulker_box",
"minecraft:green_shulker_box",
"minecraft:red_shulker_box",
"minecraft:black_shulker_box",
"minecraft:white_glazed_terracotta",
"minecraft:orange_glazed_terracotta",
"minecraft:magenta_glazed_terracotta",
"minecraft:light_blue_glazed_terracotta",
"minecraft:yellow_glazed_terracotta",
"minecraft:lime_glazed_terracotta",
"minecraft:pink_glazed_terracotta",
"minecraft:gray_glazed_terracotta",
"minecraft:light_gray_glazed_terracotta",
"minecraft:cyan_glazed_terracotta",
"minecraft:purple_glazed_terracotta",
"minecraft:blue_glazed_terracotta",
"minecraft:brown_glazed_terracotta",
"minecraft:green_glazed_terracotta",
"minecraft:red_glazed_terracotta",
"minecraft:black_glazed_terracotta",
"minecraft:concrete",
"minecraft:concrete_powder",
"minecraft:structure_block"
    }
    Public ZhBlocks As String() = {
"空气",
"石头",
"草方块",
"泥土",
"圆石",
"木板",
"树苗",
"基岩",
"水",
"静态水",
"熔岩",
"静态熔岩",
"沙子",
"沙砾",
"金矿石",
"铁矿石",
"煤矿石",
"木头",
"树叶",
"海绵",
"玻璃",
"青金石矿石",
"青金石块",
"发射器",
"砂岩",
"音符盒",
"床",
"充能铁轨",
"探测铁轨",
"粘性活塞",
"蜘蛛网",
"草丛",
"枯死的灌木",
"活塞",
"活塞臂",
"羊毛",
"蒲公英",
"虞美人",
"棕色蘑菇",
"红色蘑菇",
"金块",
"铁块",
"双石台阶",
"石台阶",
"砖块",
"TNT",
"书架",
"苔石",
"黑曜石",
"火把",
"火",
"刷怪箱",
"橡木楼梯",
"箱子",
"红石线",
"钻石矿石",
"钻石块",
"工作台",
"小麦",
"耕地",
"熔炉",
"燃烧的熔炉",
"站立的告示牌",
"橡木门",
"梯子",
"铁轨",
"圆石楼梯",
"墙上的告示牌",
"拉杆",
"石质压力板",
"铁门",
"木质压力板",
"红石矿石",
"发光的红石矿石",
"红石火把（未开启）",
"红石火把（已开启）",
"石质按钮",
"雪块",
"冰",
"雪块",
"仙人掌",
"粘土",
"甘蔗",
"唱片机",
"橡木栅栏",
"南瓜",
"地狱岩",
"灵魂沙",
"荧石",
"下界传送门",
"南瓜灯",
"蛋糕",
"红石中继器（未开启）",
"红石中继器（已开启）",
"染色玻璃",
"活板门",
"怪物蛋",
"石砖",
"棕色巨型蘑菇",
"红色巨型蘑菇",
"铁栏杆",
"玻璃板",
"西瓜片",
"南瓜梗",
"西瓜梗",
"藤蔓",
"栅栏门",
"砖块楼梯",
"石砖楼梯",
"菌丝",
"睡莲",
"地狱砖块",
"地狱砖栅栏",
"地狱砖楼梯",
"地狱疣",
"附魔台",
"酿造台",
"炼药锅",
"末地传送门方块",
"末地传送门框架",
"末地石",
"龙蛋",
"红石灯（未开启）",
"红石灯（已开启）",
"双木台阶",
"木台阶",
"可可果",
"砂岩楼梯",
"绿宝石矿石",
"末影箱",
"绊线钩",
"绊线",
"绿宝石块",
"云杉楼梯",
"桦木楼梯",
"丛林楼梯",
"命令方块",
"信标",
"圆石墙",
"花盆",
"胡萝卜",
"马铃薯",
"木质按钮",
"生物头颅",
"铁砧",
"陷阱箱",
"测重压力板（轻质）",
"测重压力板（重质）",
"红石比较器",
"红石比较器（已弃用）",
"阳光传感器",
"红石块",
"下界石英矿石",
"漏斗",
"石英块",
"石英楼梯",
"激活铁轨",
"投掷器",
"染色陶瓦",
"染色玻璃板",
"树叶（金合欢/深色橡木）",
"木头（金合欢/深色橡木）",
"金合欢楼梯",
"深色橡木楼梯",
"粘液块",
"屏障",
"铁活板门",
"海晶石",
"海晶灯",
"干草块",
"地毯",
"陶瓦",
"煤炭块",
"浮冰",
"大型花",
"站立的旗帜",
"墙上的旗帜",
"反向阳光传感器",
"红砂岩",
"红砂岩楼梯",
"双红砂岩台阶",
"红砂岩台阶",
"云杉木栅栏门",
"白桦木栅栏门",
"丛林木栅栏门",
"深色橡木栅栏门",
"金合欢栅栏门",
"云杉木栅栏",
"白桦木栅栏",
"丛林木栅栏",
"深色橡木栅栏",
"金合欢栅栏",
"云杉木门",
"白桦木门",
"丛林木门",
"金合欢木门",
"深色橡木门",
"末地烛",
"紫颂植物",
"紫颂花",
"紫珀块",
"竖纹紫珀块",
"紫珀块楼梯",
"双紫珀台阶",
"紫珀块台阶",
"末地石砖",
"甜菜种子",
"草径",
"末地折跃门方块",
"循环型命令方块",
"连锁型命令方块",
"霜冰",
"岩浆块",
"地狱疣块",
"红色地狱砖",
"骨块",
"结构空位",
"侦测器",
"白色潜影盒",
"橙色潜影盒",
"品红色潜影盒",
"淡蓝色潜影盒",
"黄色潜影盒",
"黄绿色潜影盒",
"粉红色潜影盒",
"灰色潜影盒",
"淡灰色潜影盒",
"青色潜影盒",
"紫色潜影盒",
"蓝色潜影盒",
"棕色潜影盒",
"绿色潜影盒",
"红色潜影盒",
"黑色潜影盒",
"白色带釉陶瓦",
"橙色带釉陶瓦",
"品红色带釉陶瓦",
"淡蓝色带釉陶瓦",
"黄色带釉陶瓦",
"黄绿色带釉陶瓦",
"粉红色带釉陶瓦",
"灰色带釉陶瓦",
"淡灰色带釉陶瓦",
"青色带釉陶瓦",
"紫色带釉陶瓦",
"蓝色带釉陶瓦",
"棕色带釉陶瓦",
"绿色带釉陶瓦",
"红色带釉陶瓦",
"黑色带釉陶瓦",
"混凝土",
"混凝土粉末",
"结构方块"
    }

    ' 物品ID
    ' 来自 minecraft wiki 列表
    Public EnItems As String() = {
"minecraft:iron_shovel",
"minecraft:iron_pickaxe",
"minecraft:iron_axe",
"minecraft:flint_and_steel",
"minecraft:apple",
"minecraft:bow",
"minecraft:arrow",
"minecraft:coal",
"minecraft:diamond",
"minecraft:iron_ingot",
"minecraft:gold_ingot",
"minecraft:iron_sword",
"minecraft:wooden_sword",
"minecraft:wooden_shovel",
"minecraft:wooden_pickaxe",
"minecraft:wooden_axe",
"minecraft:stone_sword",
"minecraft:stone_shovel",
"minecraft:stone_pickaxe",
"minecraft:stone_axe",
"minecraft:diamond_sword",
"minecraft:diamond_shovel",
"minecraft:diamond_pickaxe",
"minecraft:diamond_axe",
"minecraft:stick",
"minecraft:bowl",
"minecraft:mushroom_stew",
"minecraft:golden_sword",
"minecraft:golden_shovel",
"minecraft:golden_pickaxe",
"minecraft:golden_axe",
"minecraft:string",
"minecraft:feather",
"minecraft:gunpowder",
"minecraft:wooden_hoe",
"minecraft:stone_hoe",
"minecraft:iron_hoe",
"minecraft:diamond_hoe",
"minecraft:golden_hoe",
"minecraft:wheat_seeds",
"minecraft:wheat",
"minecraft:bread",
"minecraft:leather_helmet",
"minecraft:leather_chestplate",
"minecraft:leather_leggings",
"minecraft:leather_boots",
"minecraft:chainmail_helmet",
"minecraft:chainmail_chestplate",
"minecraft:chainmail_leggings",
"minecraft:chainmail_boots",
"minecraft:iron_helmet",
"minecraft:iron_chestplate",
"minecraft:iron_leggings",
"minecraft:iron_boots",
"minecraft:diamond_helmet",
"minecraft:diamond_chestplate",
"minecraft:diamond_leggings",
"minecraft:diamond_boots",
"minecraft:golden_helmet",
"minecraft:golden_chestplate",
"minecraft:golden_leggings",
"minecraft:golden_boots",
"minecraft:flint",
"minecraft:porkchop",
"minecraft:cooked_porkchop",
"minecraft:painting",
"minecraft:golden_apple",
"minecraft:sign",
"minecraft:wooden_door",
"minecraft:bucket",
"minecraft:water_bucket",
"minecraft:lava_bucket",
"minecraft:minecart",
"minecraft:saddle",
"minecraft:iron_door",
"minecraft:redstone",
"minecraft:snowball",
"minecraft:boat",
"minecraft:leather",
"minecraft:milk_bucket",
"minecraft:brick",
"minecraft:clay_ball",
"minecraft:reeds",
"minecraft:paper",
"minecraft:book",
"minecraft:slime_ball",
"minecraft:chest_minecart",
"minecraft:furnace_minecart",
"minecraft:egg",
"minecraft:compass",
"minecraft:fishing_rod",
"minecraft:clock",
"minecraft:glowstone_dust",
"minecraft:fish",
"minecraft:cooked_fish",
"minecraft:dye",
"minecraft:bone",
"minecraft:sugar",
"minecraft:cake",
"minecraft:bed",
"minecraft:repeater",
"minecraft:cookie",
"minecraft:filled_map",
"minecraft:shears",
"minecraft:melon",
"minecraft:pumpkin_seeds",
"minecraft:melon_seeds",
"minecraft:beef",
"minecraft:cooked_beef",
"minecraft:chicken",
"minecraft:cooked_chicken",
"minecraft:rotten_flesh",
"minecraft:ender_pearl",
"minecraft:blaze_rod",
"minecraft:ghast_tear",
"minecraft:gold_nugget",
"minecraft:nether_wart",
"minecraft:potion",
"minecraft:glass_bottle",
"minecraft:spider_eye",
"minecraft:fermented_spider_eye",
"minecraft:blaze_powder",
"minecraft:magma_cream",
"minecraft:brewing_stand",
"minecraft:cauldron",
"minecraft:ender_eye",
"minecraft:speckled_melon",
"minecraft:spawn_egg",
"minecraft:experience_bottle",
"minecraft:fire_charge",
"minecraft:writable_book",
"minecraft:written_book",
"minecraft:emerald",
"minecraft:item_frame",
"minecraft:flower_pot",
"minecraft:carrot",
"minecraft:potato",
"minecraft:baked_potato",
"minecraft:poisonous_potato",
"minecraft:map",
"minecraft:golden_carrot",
"minecraft:skull",
"minecraft:carrot_on_a_stick",
"minecraft:nether_star",
"minecraft:pumpkin_pie",
"minecraft:fireworks",
"minecraft:firework_charge",
"minecraft:enchanted_book",
"minecraft:comparator",
"minecraft:netherbrick",
"minecraft:quartz",
"minecraft:tnt_minecart",
"minecraft:hopper_minecart",
"minecraft:prismarine_shard",
"minecraft:prismarine_crystals",
"minecraft:rabbit",
"minecraft:cooked_rabbit",
"minecraft:rabbit_stew",
"minecraft:rabbit_foot",
"minecraft:rabbit_hide",
"minecraft:armor_stand",
"minecraft:iron_horse_armor",
"minecraft:golden_horse_armor",
"minecraft:diamond_horse_armor",
"minecraft:lead",
"minecraft:name_tag",
"minecraft:command_block_minecart",
"minecraft:mutton",
"minecraft:cooked_mutton",
"minecraft:banner",
"minecraft:end_crystal",
"minecraft:spruce_door",
"minecraft:birch_door",
"minecraft:jungle_door",
"minecraft:acacia_door",
"minecraft:dark_oak_door",
"minecraft:chorus_fruit",
"minecraft:chorus_fruit_popped",
"minecraft:beetroot",
"minecraft:beetroot_seeds",
"minecraft:beetroot_soup",
"minecraft:dragon_breath",
"minecraft:splash_potion",
"minecraft:spectral_arrow",
"minecraft:tipped_arrow",
"minecraft:lingering_potion",
"minecraft:shield",
"minecraft:elytra",
"minecraft:spruce_boat",
"minecraft:birch_boat",
"minecraft:jungle_boat",
"minecraft:acacia_boat",
"minecraft:dark_oak_boat",
"minecraft:totem_of_undying",
"minecraft:shulker_shell",
"minecraft:iron_nugget",
"minecraft:record_13",
"minecraft:record_cat",
"minecraft:record_blocks",
"minecraft:record_chirp",
"minecraft:record_far",
"minecraft:record_mall",
"minecraft:record_mellohi",
"minecraft:record_stal",
"minecraft:record_strad",
"minecraft:record_ward",
"minecraft:record_11",
"minecraft:record_wait"
    }
    Public ZhItems As String() = {
"铁锹",
"铁镐",
"铁斧",
"打火石",
"苹果",
"弓",
"箭",
"煤炭",
"钻石",
"铁锭",
"金锭",
"铁剑",
"木剑",
"木锹",
"木镐",
"木斧",
"石剑",
"石锹",
"石镐",
"石斧",
"钻石剑",
"钻石锹",
"钻石镐",
"钻石斧",
"木棍",
"碗",
"蘑菇煲",
"金剑",
"金锹",
"金镐",
"金斧",
"线",
"羽毛",
"火药",
"木锄",
"石锄",
"铁锄",
"钻石锄",
"金锄",
"小麦种子",
"小麦",
"面包",
"皮革帽子",
"皮革外套",
"皮革裤子",
"皮革靴子",
"锁链头盔",
"锁链胸甲",
"锁链护腿",
"锁链靴子",
"铁头盔",
"铁胸甲",
"铁护腿",
"铁靴子",
"钻石头盔",
"钻石胸甲",
"钻石护腿",
"钻石靴子",
"金头盔",
"金胸甲",
"金护腿",
"金靴子",
"燧石",
"生猪排",
"熟猪排",
"画",
"金苹果",
"告示牌",
"橡木门",
"桶",
"水桶",
"熔岩桶",
"矿车",
"鞍",
"铁门",
"红石粉",
"雪球",
"船",
"皮革",
"牛奶",
"红砖",
"粘土",
"甘蔗",
"纸",
"书",
"粘液球",
"运输矿车",
"动力矿车",
"鸡蛋",
"指南针",
"钓鱼竿",
"钟",
"荧石粉",
"生鱼",
"熟鱼",
"染料",
"骨头",
"糖",
"蛋糕",
"床",
"红石中继器",
"曲奇",
"地图",
"剪刀",
"西瓜片",
"南瓜种子",
"西瓜种子",
"生牛肉",
"牛排",
"生鸡肉",
"熟鸡肉",
"腐肉",
"末影珍珠",
"烈焰棒",
"恶魂之泪",
"金粒",
"地狱疣",
"药水",
"玻璃瓶",
"蜘蛛眼",
"发酵蛛眼",
"烈焰粉",
"岩浆膏",
"酿造台",
"炼药锅",
"末影之眼",
"闪烁的西瓜",
"刷怪蛋",
"附魔之瓶",
"火焰弹",
"书与笔",
"成书",
"绿宝石",
"物品展示框",
"花盆",
"胡萝卜",
"马铃薯",
"烤马铃薯",
"毒马铃薯",
"空地图",
"金胡萝卜",
"生物头颅",
"胡萝卜钓竿",
"下界之星",
"南瓜派",
"烟花火箭",
"烟火之星",
"附魔书",
"红石比较器",
"地狱砖块",
"下界石英",
"TNT矿车",
"漏斗矿车",
"海晶碎片",
"海晶砂粒",
"生兔肉",
"熟兔肉",
"兔肉煲",
"兔子脚",
"兔子皮",
"盔甲架",
"铁马铠",
"金马铠",
"钻石马铠",
"拴绳",
"命名牌",
"命令方块矿车",
"生羊肉",
"熟羊肉",
"旗帜",
"末影水晶",
"云杉木门",
"白桦木门",
"丛林木门",
"金合欢木门",
"深色橡木门",
"紫颂果",
"爆裂紫颂果",
"甜菜根",
"甜菜种子",
"甜菜汤",
"龙息",
"喷溅药水",
"光灵箭",
"药箭",
"滞留药水",
"盾牌",
"鞘翅",
"云杉木船",
"白桦木船",
"丛林木船",
"金合欢木船",
"深色橡木船",
"不死图腾",
"潜影壳（未使用）",
"铁粒",
"13唱片",
"cat唱片",
"blocks唱片",
"chirp唱片",
"far唱片",
"mall唱片",
"mellohi唱片",
"stal唱片",
"strad唱片",
"ward唱片",
"11唱片",
"wait唱片"
    }

    ' 配方列表
    ' 来自按 TAB 后的 latest.log 文件
    Public EnRecipes As String() = {
"minecraft:acacia_boat",
"minecraft:acacia_door",
"minecraft:acacia_fence",
"minecraft:acacia_fence_gate",
"minecraft:acacia_planks",
"minecraft:acacia_stairs",
"minecraft:acacia_wooden_slab",
"minecraft:activator_rail",
"minecraft:andesite",
"minecraft:anvil",
"minecraft:armor_stand",
"minecraft:armordye",
"minecraft:arrow",
"minecraft:banneraddpattern",
"minecraft:bannerduplicate",
"minecraft:beacon",
"minecraft:beetroot_soup",
"minecraft:birch_boat",
"minecraft:birch_door",
"minecraft:birch_fence",
"minecraft:birch_fence_gate",
"minecraft:birch_planks",
"minecraft:birch_stairs",
"minecraft:birch_wooden_slab",
"minecraft:black_banner",
"minecraft:black_bed",
"minecraft:black_bed_from_white_bed",
"minecraft:black_carpet",
"minecraft:black_concrete_powder",
"minecraft:black_stained_glass",
"minecraft:black_stained_glass_pane",
"minecraft:black_stained_hardened_clay",
"minecraft:black_wool",
"minecraft:blaze_powder",
"minecraft:blue_banner",
"minecraft:blue_bed",
"minecraft:blue_bed_from_white_bed",
"minecraft:blue_carpet",
"minecraft:blue_concrete_powder",
"minecraft:blue_stained_glass",
"minecraft:blue_stained_glass_pane",
"minecraft:blue_stained_hardened_clay",
"minecraft:blue_wool",
"minecraft:boat",
"minecraft:bone_block",
"minecraft:bone_meal_from_block",
"minecraft:bone_meal_from_bone",
"minecraft:book",
"minecraft:bookcloning",
"minecraft:bookshelf",
"minecraft:bow",
"minecraft:bowl",
"minecraft:bread",
"minecraft:brewing_stand",
"minecraft:brick_block",
"minecraft:brick_slab",
"minecraft:brick_stairs",
"minecraft:brown_banner",
"minecraft:brown_bed",
"minecraft:brown_bed_from_white_bed",
"minecraft:brown_carpet",
"minecraft:brown_concrete_powder",
"minecraft:brown_stained_glass",
"minecraft:brown_stained_glass_pane",
"minecraft:brown_stained_hardened_clay",
"minecraft:brown_wool",
"minecraft:bucket",
"minecraft:cake",
"minecraft:carrot_on_a_stick",
"minecraft:cauldron",
"minecraft:chest",
"minecraft:chest_minecart",
"minecraft:chiseled_quartz_block",
"minecraft:chiseled_red_sandstone",
"minecraft:chiseled_sandstone",
"minecraft:chiseled_stonebrick",
"minecraft:clay",
"minecraft:clock",
"minecraft:coal",
"minecraft:coal_block",
"minecraft:coarse_dirt",
"minecraft:cobblestone_slab",
"minecraft:cobblestone_wall",
"minecraft:comparator",
"minecraft:compass",
"minecraft:cookie",
"minecraft:crafting_table",
"minecraft:cyan_banner",
"minecraft:cyan_bed",
"minecraft:cyan_bed_from_white_bed",
"minecraft:cyan_carpet",
"minecraft:cyan_concrete_powder",
"minecraft:cyan_dye",
"minecraft:cyan_stained_glass",
"minecraft:cyan_stained_glass_pane",
"minecraft:cyan_stained_hardened_clay",
"minecraft:cyan_wool",
"minecraft:dark_oak_boat",
"minecraft:dark_oak_door",
"minecraft:dark_oak_fence",
"minecraft:dark_oak_fence_gate",
"minecraft:dark_oak_planks",
"minecraft:dark_oak_stairs",
"minecraft:dark_oak_wooden_slab",
"minecraft:dark_prismarine",
"minecraft:daylight_detector",
"minecraft:detector_rail",
"minecraft:diamond",
"minecraft:diamond_axe",
"minecraft:diamond_block",
"minecraft:diamond_boots",
"minecraft:diamond_chestplate",
"minecraft:diamond_helmet",
"minecraft:diamond_hoe",
"minecraft:diamond_leggings",
"minecraft:diamond_pickaxe",
"minecraft:diamond_shovel",
"minecraft:diamond_sword",
"minecraft:diorite",
"minecraft:dispenser",
"minecraft:dropper",
"minecraft:emerald",
"minecraft:emerald_block",
"minecraft:enchanting_table",
"minecraft:end_bricks",
"minecraft:end_crystal",
"minecraft:end_rod",
"minecraft:ender_chest",
"minecraft:ender_eye",
"minecraft:fence",
"minecraft:fence_gate",
"minecraft:fermented_spider_eye",
"minecraft:fire_charge",
"minecraft:fireworks",
"minecraft:fishing_rod",
"minecraft:flint_and_steel",
"minecraft:flower_pot",
"minecraft:furnace",
"minecraft:furnace_minecart",
"minecraft:glass_bottle",
"minecraft:glass_pane",
"minecraft:glowstone",
"minecraft:gold_block",
"minecraft:gold_ingot_from_block",
"minecraft:gold_ingot_from_nuggets",
"minecraft:gold_nugget",
"minecraft:golden_apple",
"minecraft:golden_axe",
"minecraft:golden_boots",
"minecraft:golden_carrot",
"minecraft:golden_chestplate",
"minecraft:golden_helmet",
"minecraft:golden_hoe",
"minecraft:golden_leggings",
"minecraft:golden_pickaxe",
"minecraft:golden_rail",
"minecraft:golden_shovel",
"minecraft:golden_sword",
"minecraft:granite",
"minecraft:gray_banner",
"minecraft:gray_bed",
"minecraft:gray_bed_from_white_bed",
"minecraft:gray_carpet",
"minecraft:gray_concrete_powder",
"minecraft:gray_dye",
"minecraft:gray_stained_glass",
"minecraft:gray_stained_glass_pane",
"minecraft:gray_stained_hardened_clay",
"minecraft:gray_wool",
"minecraft:green_banner",
"minecraft:green_bed",
"minecraft:green_bed_from_white_bed",
"minecraft:green_carpet",
"minecraft:green_concrete_powder",
"minecraft:green_stained_glass",
"minecraft:green_stained_glass_pane",
"minecraft:green_stained_hardened_clay",
"minecraft:green_wool",
"minecraft:hay_block",
"minecraft:heavy_weighted_pressure_plate",
"minecraft:hopper",
"minecraft:hopper_minecart",
"minecraft:iron_axe",
"minecraft:iron_bars",
"minecraft:iron_block",
"minecraft:iron_boots",
"minecraft:iron_chestplate",
"minecraft:iron_door",
"minecraft:iron_helmet",
"minecraft:iron_hoe",
"minecraft:iron_ingot_from_block",
"minecraft:iron_ingot_from_nuggets",
"minecraft:iron_leggings",
"minecraft:iron_nugget",
"minecraft:iron_pickaxe",
"minecraft:iron_shovel",
"minecraft:iron_sword",
"minecraft:iron_trapdoor",
"minecraft:item_frame",
"minecraft:jukebox",
"minecraft:jungle_boat",
"minecraft:jungle_door",
"minecraft:jungle_fence",
"minecraft:jungle_fence_gate",
"minecraft:jungle_planks",
"minecraft:jungle_stairs",
"minecraft:jungle_wooden_slab",
"minecraft:ladder",
"minecraft:lapis_block",
"minecraft:lapis_lazuli",
"minecraft:lead",
"minecraft:leather",
"minecraft:leather_boots",
"minecraft:leather_chestplate",
"minecraft:leather_helmet",
"minecraft:leather_leggings",
"minecraft:lever",
"minecraft:light_blue_banner",
"minecraft:light_blue_bed",
"minecraft:light_blue_bed_from_white_bed",
"minecraft:light_blue_carpet",
"minecraft:light_blue_concrete_powder",
"minecraft:light_blue_dye_from_blue_orchid",
"minecraft:light_blue_dye_from_lapis_bonemeal",
"minecraft:light_blue_stained_glass",
"minecraft:light_blue_stained_glass_pane",
"minecraft:light_blue_stained_hardened_clay",
"minecraft:light_blue_wool",
"minecraft:light_gray_banner",
"minecraft:light_gray_bed",
"minecraft:light_gray_bed_from_white_bed",
"minecraft:light_gray_carpet",
"minecraft:light_gray_concrete_powder",
"minecraft:light_gray_dye_from_azure_bluet",
"minecraft:light_gray_dye_from_gray_bonemeal",
"minecraft:light_gray_dye_from_ink_bonemeal",
"minecraft:light_gray_dye_from_oxeye_daisy",
"minecraft:light_gray_dye_from_white_tulip",
"minecraft:light_gray_stained_glass",
"minecraft:light_gray_stained_glass_pane",
"minecraft:light_gray_stained_hardened_clay",
"minecraft:light_gray_wool",
"minecraft:light_weighted_pressure_plate",
"minecraft:lime_banner",
"minecraft:lime_bed",
"minecraft:lime_bed_from_white_bed",
"minecraft:lime_carpet",
"minecraft:lime_concrete_powder",
"minecraft:lime_dye",
"minecraft:lime_stained_glass",
"minecraft:lime_stained_glass_pane",
"minecraft:lime_stained_hardened_clay",
"minecraft:lime_wool",
"minecraft:lit_pumpkin",
"minecraft:magenta_banner",
"minecraft:magenta_bed",
"minecraft:magenta_bed_from_white_bed",
"minecraft:magenta_carpet",
"minecraft:magenta_concrete_powder",
"minecraft:magenta_dye_from_allium",
"minecraft:magenta_dye_from_lapis_ink_bonemeal",
"minecraft:magenta_dye_from_lapis_red_pink",
"minecraft:magenta_dye_from_lilac",
"minecraft:magenta_dye_from_purple_and_pink",
"minecraft:magenta_stained_glass",
"minecraft:magenta_stained_glass_pane",
"minecraft:magenta_stained_hardened_clay",
"minecraft:magenta_wool",
"minecraft:magma",
"minecraft:magma_cream",
"minecraft:map",
"minecraft:mapcloning",
"minecraft:mapextending",
"minecraft:melon_block",
"minecraft:melon_seeds",
"minecraft:minecart",
"minecraft:mossy_cobblestone",
"minecraft:mossy_cobblestone_wall",
"minecraft:mossy_stonebrick",
"minecraft:mushroom_stew",
"minecraft:nether_brick",
"minecraft:nether_brick_fence",
"minecraft:nether_brick_slab",
"minecraft:nether_brick_stairs",
"minecraft:nether_wart_block",
"minecraft:noteblock",
"minecraft:oak_planks",
"minecraft:oak_stairs",
"minecraft:oak_wooden_slab",
"minecraft:observer",
"minecraft:orange_banner",
"minecraft:orange_bed",
"minecraft:orange_bed_from_white_bed",
"minecraft:orange_carpet",
"minecraft:orange_concrete_powder",
"minecraft:orange_dye_from_orange_tulip",
"minecraft:orange_dye_from_red_yellow",
"minecraft:orange_stained_glass",
"minecraft:orange_stained_glass_pane",
"minecraft:orange_stained_hardened_clay",
"minecraft:orange_wool",
"minecraft:painting",
"minecraft:paper",
"minecraft:pillar_quartz_block",
"minecraft:pink_banner",
"minecraft:pink_bed",
"minecraft:pink_bed_from_white_bed",
"minecraft:pink_carpet",
"minecraft:pink_concrete_powder",
"minecraft:pink_dye_from_peony",
"minecraft:pink_dye_from_pink_tulip",
"minecraft:pink_dye_from_red_bonemeal",
"minecraft:pink_stained_glass",
"minecraft:pink_stained_glass_pane",
"minecraft:pink_stained_hardened_clay",
"minecraft:pink_wool",
"minecraft:piston",
"minecraft:polished_andesite",
"minecraft:polished_diorite",
"minecraft:polished_granite",
"minecraft:prismarine",
"minecraft:prismarine_bricks",
"minecraft:pumpkin_pie",
"minecraft:pumpkin_seeds",
"minecraft:purple_banner",
"minecraft:purple_bed",
"minecraft:purple_bed_from_white_bed",
"minecraft:purple_carpet",
"minecraft:purple_concrete_powder",
"minecraft:purple_dye",
"minecraft:purple_shulker_box",
"minecraft:purple_stained_glass",
"minecraft:purple_stained_glass_pane",
"minecraft:purple_stained_hardened_clay",
"minecraft:purple_wool",
"minecraft:purpur_block",
"minecraft:purpur_pillar",
"minecraft:purpur_slab",
"minecraft:purpur_stairs",
"minecraft:quartz_block",
"minecraft:quartz_slab",
"minecraft:quartz_stairs",
"minecraft:rabbit_stew_from_brown_mushroom",
"minecraft:rabbit_stew_from_red_mushroom",
"minecraft:rail",
"minecraft:red_banner",
"minecraft:red_bed",
"minecraft:red_bed_from_white_bed",
"minecraft:red_carpet",
"minecraft:red_concrete_powder",
"minecraft:red_dye_from_beetroot",
"minecraft:red_dye_from_poppy",
"minecraft:red_dye_from_rose_bush",
"minecraft:red_dye_from_tulip",
"minecraft:red_nether_brick",
"minecraft:red_sandstone",
"minecraft:red_sandstone_slab",
"minecraft:red_sandstone_stairs",
"minecraft:red_stained_glass",
"minecraft:red_stained_glass_pane",
"minecraft:red_stained_hardened_clay",
"minecraft:red_wool",
"minecraft:redstone",
"minecraft:redstone_block",
"minecraft:redstone_lamp",
"minecraft:redstone_torch",
"minecraft:repairitem",
"minecraft:repeater",
"minecraft:sandstone",
"minecraft:sandstone_slab",
"minecraft:sandstone_stairs",
"minecraft:sea_lantern",
"minecraft:shears",
"minecraft:shield",
"minecraft:shielddecoration",
"minecraft:shulkerboxcoloring",
"minecraft:sign",
"minecraft:slime",
"minecraft:slime_ball",
"minecraft:smooth_red_sandstone",
"minecraft:smooth_sandstone",
"minecraft:snow",
"minecraft:snow_layer",
"minecraft:speckled_melon",
"minecraft:spectral_arrow",
"minecraft:spruce_boat",
"minecraft:spruce_door",
"minecraft:spruce_fence",
"minecraft:spruce_fence_gate",
"minecraft:spruce_planks",
"minecraft:spruce_stairs",
"minecraft:spruce_wooden_slab",
"minecraft:stick",
"minecraft:sticky_piston",
"minecraft:stone_axe",
"minecraft:stone_brick_slab",
"minecraft:stone_brick_stairs",
"minecraft:stone_button",
"minecraft:stone_hoe",
"minecraft:stone_pickaxe",
"minecraft:stone_pressure_plate",
"minecraft:stone_shovel",
"minecraft:stone_slab",
"minecraft:stone_stairs",
"minecraft:stone_sword",
"minecraft:stonebrick",
"minecraft:string_to_wool",
"minecraft:sugar",
"minecraft:tippedarrow",
"minecraft:tnt",
"minecraft:tnt_minecart",
"minecraft:torch",
"minecraft:trapdoor",
"minecraft:trapped_chest",
"minecraft:tripwire_hook",
"minecraft:wheat",
"minecraft:white_banner",
"minecraft:white_bed",
"minecraft:white_carpet",
"minecraft:white_concrete_powder",
"minecraft:white_stained_glass",
"minecraft:white_stained_glass_pane",
"minecraft:white_stained_hardened_clay",
"minecraft:wooden_axe",
"minecraft:wooden_button",
"minecraft:wooden_door",
"minecraft:wooden_hoe",
"minecraft:wooden_pickaxe",
"minecraft:wooden_pressure_plate",
"minecraft:wooden_shovel",
"minecraft:wooden_sword",
"minecraft:writable_book",
"minecraft:yellow_banner",
"minecraft:yellow_bed",
"minecraft:yellow_bed_from_white_bed",
"minecraft:yellow_carpet",
"minecraft:yellow_concrete_powder",
"minecraft:yellow_dye_from_dandelion",
"minecraft:yellow_dye_from_sunflower",
"minecraft:yellow_stained_glass",
"minecraft:yellow_stained_glass_pane",
"minecraft:yellow_stained_hardened_clay",
"minecraft:yellow_wool"
    }
    Public ZhRecipes As String() = {
"金合欢 船",
"金合欢 门",
"金合欢 fence",
"金合欢 fence gate",
"金合欢 planks",
"金合欢 楼梯",
"金合欢 木 slab",
"activator rail",
"andesite",
"anvil",
"armor stand",
"armordye",
"arrow",
"banneraddpattern",
"bannerduplicate",
"beacon",
"beetroot soup",
"birch 船",
"birch 门",
"birch fence",
"birch fence gate",
"birch planks",
"birch 楼梯",
"birch 木 slab",
"黑色 banner",
"黑色 床",
"黑色 床 从 白色 床",
"黑色 carpet",
"黑色 concrete powder",
"黑色 染色 玻璃",
"黑色 染色 玻璃板",
"黑色 染色 硬化 粘土",
"黑色 羊毛",
"blaze powder",
"蓝色 banner",
"蓝色 床",
"蓝色 床 从 白色 床",
"蓝色 carpet",
"蓝色 concrete powder",
"蓝色 染色 玻璃",
"蓝色 染色 玻璃板",
"蓝色 染色 硬化 粘土",
"蓝色 羊毛",
"船",
"骨 块",
"骨粉 从 块",
"骨粉 从 骨",
"book",
"bookcloning",
"bookshelf",
"bow",
"bowl",
"bread",
"brewing stand",
"砖 块",
"砖 slab",
"砖 楼梯",
"brown banner",
"brown 床",
"brown 床 从 白色 床",
"brown carpet",
"brown concrete powder",
"brown 染色 玻璃",
"brown 染色 玻璃板",
"brown 染色 硬化 粘土",
"brown 羊毛",
"bucket",
"cake",
"carrot on a stick",
"cauldron",
"箱子",
"箱子 矿车",
"chiseled 石英 块",
"chiseled 红色 沙石",
"chiseled 沙石",
"chiseled 石砖",
"clay",
"clock",
"coal",
"coal 块",
"coarse dirt",
"圆石 slab",
"圆石 围墙",
"comparator",
"compass",
"cookie",
"crafting table",
"cyan banner",
"cyan 床",
"cyan 床 从 白色 床",
"cyan carpet",
"cyan concrete powder",
"cyan dye",
"cyan 染色 玻璃",
"cyan 染色 玻璃板",
"cyan 染色 硬化 粘土",
"cyan 羊毛",
"深 橡木 船",
"深 橡木 门",
"深 橡木 fence",
"深 橡木 fence gate",
"深 橡木 planks",
"深 橡木 楼梯",
"深 橡木 木 slab",
"深 prismarine",
"daylight detector",
"detector rail",
"钻石",
"钻石 斧",
"钻石 块",
"钻石 boots",
"钻石 箱子plate",
"钻石 helmet",
"钻石 hoe",
"钻石 leggings",
"钻石 镐",
"钻石 铲子",
"钻石 sword",
"diorite",
"dispenser",
"dropper",
"emerald",
"emerald 块",
"enchanting table",
"end 砖s",
"end crystal",
"end rod",
"ender 箱子",
"ender eye",
"fence",
"fence gate",
"fermented spider eye",
"fire charge",
"fireworks",
"fishing rod",
"flint and steel",
"flower pot",
"furnace",
"furnace 矿车",
"玻璃 bottle",
"玻璃板",
"glow石",
"金 块",
"金 ingot 从 块",
"金 ingot 从 nuggets",
"金 nugget",
"金 apple",
"金 斧",
"金 boots",
"金 carrot",
"金 箱子plate",
"金 helmet",
"金 hoe",
"金 leggings",
"金 镐",
"金 rail",
"金 铲子",
"金 sword",
"granite",
"灰色 banner",
"灰色 床",
"灰色 床 从 白色 床",
"灰色 carpet",
"灰色 concrete powder",
"灰色 dye",
"灰色 染色 玻璃",
"灰色 染色 玻璃板",
"灰色 染色 硬化 粘土",
"灰色 羊毛",
"green banner",
"green 床",
"green 床 从 白色 床",
"green carpet",
"green concrete powder",
"green 染色 玻璃",
"green 染色 玻璃板",
"green 染色 硬化 粘土",
"green 羊毛",
"hay 块",
"heavy weighted pressure plate",
"hopper",
"hopper 矿车",
"铁 斧",
"铁 bars",
"铁 块",
"铁 boots",
"铁 箱子plate",
"铁 门",
"铁 helmet",
"铁 hoe",
"铁 ingot 从 块",
"铁 ingot 从 nuggets",
"铁 leggings",
"铁 nugget",
"铁 镐",
"铁 铲子",
"铁 sword",
"铁 trap门",
"item frame",
"jukebox",
"jungle 船",
"jungle 门",
"jungle fence",
"jungle fence gate",
"jungle planks",
"jungle 楼梯",
"jungle 木 slab",
"ladder",
"lapis 块",
"lapis lazuli",
"lead",
"leather",
"leather boots",
"leather 箱子plate",
"leather helmet",
"leather leggings",
"lever",
"淡 蓝色 banner",
"淡 蓝色 床",
"淡 蓝色 床 从 白色 床",
"淡 蓝色 carpet",
"淡 蓝色 concrete powder",
"淡 蓝色染料从 蓝色 orchid",
"淡 蓝色染料从 lapis 骨meal",
"淡 蓝色 染色 玻璃",
"淡 蓝色 染色 玻璃板",
"淡 蓝色 染色 硬化 粘土",
"淡 蓝色 羊毛",
"淡 灰色 banner",
"淡 灰色 床",
"淡 灰色 床 从 白色 床",
"淡 灰色 carpet",
"淡 灰色 concrete powder",
"淡 灰色染料从 azure 蓝色t",
"淡 灰色染料从 灰色 骨meal",
"淡 灰色染料从 ink 骨meal",
"淡 灰色染料从 oxeye daisy",
"淡 灰色染料从 白色 tulip",
"淡 灰色 染色 玻璃",
"淡 灰色 染色 玻璃板",
"淡 灰色 染色 硬化 粘土",
"淡 灰色 羊毛",
"淡 weighted pressure plate",
"黄绿色 banner",
"黄绿色 床",
"黄绿色 床 从 白色 床",
"黄绿色 carpet",
"黄绿色 concrete powder",
"黄绿色 dye",
"黄绿色 染色 玻璃",
"黄绿色 染色 玻璃板",
"黄绿色 染色 硬化 粘土",
"黄绿色 羊毛",
"lit pumpkin",
"品红色 banner",
"品红色 床",
"品红色 床 从 白色 床",
"品红色 carpet",
"品红色 concrete powder",
"品红色染料从 allium",
"品红色染料从 lapis ink 骨meal",
"品红色染料从 lapis 红色 粉色",
"品红色染料从 lilac",
"品红色染料从 紫色 and 粉色",
"品红色 染色 玻璃",
"品红色 染色 玻璃板",
"品红色 染色 硬化 粘土",
"品红色 羊毛",
"magma",
"magma cream",
"map",
"mapcloning",
"mapextending",
"melon 块",
"melon seeds",
"矿车",
"苔 圆石",
"苔 圆石 围墙",
"苔 石砖",
"蘑菇 stew",
"地狱 砖",
"地狱 砖 fence",
"地狱 砖 slab",
"地狱 砖 楼梯",
"地狱 wart 块",
"note块",
"橡木 planks",
"橡木 楼梯",
"橡木 木 slab",
"观察者",
"橙色 banner",
"橙色 床",
"橙色 床 从 白色 床",
"橙色 carpet",
"橙色 concrete powder",
"橙色染料从 橙色 tulip",
"橙色染料从 红色 黄色",
"橙色 染色 玻璃",
"橙色 染色 玻璃板",
"橙色 染色 硬化 粘土",
"橙色 羊毛",
"painting",
"paper",
"pillar 石英 块",
"粉色 banner",
"粉色 床",
"粉色 床 从 白色 床",
"粉色 carpet",
"粉色 concrete powder",
"粉色染料从 牡丹",
"粉色染料从 粉色 tulip",
"粉色染料从 红色 骨meal",
"粉色 染色 玻璃",
"粉色 染色 玻璃板",
"粉色 染色 硬化 粘土",
"粉色 羊毛",
"piston",
"polished andesite",
"polished diorite",
"polished granite",
"prismarine",
"prismarine 砖s",
"pumpkin pie",
"pumpkin seeds",
"紫色 banner",
"紫色 床",
"紫色 床 从 白色 床",
"紫色 carpet",
"紫色 concrete powder",
"紫色 dye",
"紫色 shulker box",
"紫色 染色 玻璃",
"紫色 染色 玻璃板",
"紫色 染色 硬化 粘土",
"紫色 羊毛",
"purpur 块",
"purpur pillar",
"purpur slab",
"purpur 楼梯",
"石英 块",
"石英 slab",
"石英 楼梯",
"rabbit stew 从 brown 蘑菇",
"rabbit stew 从 红色 蘑菇",
"rail",
"红色 banner",
"红色 床",
"红色 床 从 白色 床",
"红色 carpet",
"红色 concrete powder",
"红色染料从 beetroot",
"红色染料从 poppy",
"红色染料从 rose bush",
"红色染料从 tulip",
"红色 地狱 砖",
"红色 沙石",
"红色 沙石 slab",
"红色 沙石 楼梯",
"红色 染色 玻璃",
"红色 染色 玻璃板",
"红色 染色 硬化 粘土",
"红色 羊毛",
"红色石",
"红色石 块",
"红色石 lamp",
"红色石 torch",
"repairitem",
"repeater",
"沙石",
"沙石 slab",
"沙石 楼梯",
"sea lantern",
"shears",
"shield",
"shielddecoration",
"shulkerboxcoloring",
"sign",
"s黄绿色",
"s黄绿色 ball",
"平滑 红色 沙石",
"平滑 沙石",
"snow",
"snow layer",
"speckled melon",
"spectral arrow",
"云杉木 船",
"云杉木 门",
"云杉木 fence",
"云杉木 fence gate",
"云杉木 planks",
"云杉木 楼梯",
"云杉木 木 slab",
"stick",
"sticky piston",
"石 斧",
"石 砖 slab",
"石 砖 楼梯",
"石 按钮",
"石 hoe",
"石 镐",
"石 pressure plate",
"石 铲子",
"石 slab",
"石 楼梯",
"石 sword",
"石砖",
"string to 羊毛",
"sugar",
"tippedarrow",
"tnt",
"tnt 矿车",
"torch",
"trap门",
"trapped 箱子",
"tripwire hook",
"wheat",
"白色 banner",
"白色 床",
"白色 carpet",
"白色 concrete powder",
"白色 染色 玻璃",
"白色 染色 玻璃板",
"白色 染色 硬化 粘土",
"木 斧",
"木 按钮",
"木 门",
"木 hoe",
"木 镐",
"木 pressure plate",
"木 铲子",
"木 sword",
"书与笔",
"黄色 banner",
"黄色 床",
"黄色 床 从 白色 床",
"黄色 carpet",
"黄色 concrete powder",
"黄色染料从 dandelion",
"黄色染料从 sunflower",
"黄色 染色 玻璃",
"黄色 染色 玻璃板",
"黄色 染色 硬化 粘土",
"黄色 羊毛"
    }

    ' 进度列表
    ' 来自 minecraft wiki 列表
    Public EnAdvancements As String() = {
"minecraft:story/root",
"minecraft:story/mine_stone",
"minecraft:story/upgrade_tools",
"minecraft:story/smelt_iron",
"minecraft:story/obtain_armor",
"minecraft:story/lava_bucket",
"minecraft:story/iron_tools",
"minecraft:story/deflect_arrow",
"minecraft:story/form_obsidian",
"minecraft:story/mine_diamond",
"minecraft:story/enter_the_nether",
"minecraft:story/shiny_gear",
"minecraft:story/enchant_item",
"minecraft:story/cure_zombie_villager",
"minecraft:story/follow_ender_eye",
"minecraft:story/enter_the_end",
"minecraft:nether/root",
"minecraft:nether/fast_travel",
"minecraft:nether/find_fortress",
"minecraft:nether/return_to_sender",
"minecraft:nether/obtain_blaze_rod",
"minecraft:nether/get_wither_skull",
"minecraft:nether/uneasy_alliance",
"minecraft:nether/brew_potion",
"minecraft:nether/summon_wither",
"minecraft:nether/create_beacon",
"minecraft:nether/all_effects",
"minecraft:nether/create_full_beacon",
"minecraft:end/root",
"minecraft:end/kill_dragon",
"minecraft:end/dragon_egg",
"minecraft:end/enter_end_gateway",
"minecraft:end/respawn_dragon",
"minecraft:end/dragon_breath",
"minecraft:end/find_end_city",
"minecraft:end/elytra",
"minecraft:end/levitate",
"minecraft:adventure/root",
"minecraft:adventure/kill_a_mob",
"minecraft:adventure/trade",
"minecraft:adventure/sleep_in_bed",
"minecraft:adventure/shoot_arrow",
"minecraft:adventure/kill_all_mobs",
"minecraft:adventure/totem_of_undying",
"minecraft:adventure/summon_iron_golem",
"minecraft:adventure/adventuring_time",
"minecraft:adventure/sniper_duel",
"minecraft:husbandry/root",
"minecraft:husbandry/breed_an_animal",
"minecraft:husbandry/tame_an_animal",
"minecraft:husbandry/plant_seed",
"minecraft:husbandry/breed_all_animals",
"minecraft:husbandry/balanced_diet",
"minecraft:husbandry/break_diamond_hoe"
    }
    Public ZhAdvancements As String() = {
"Minecraft",
"石器时代",
"获得升级",
"来硬的",
"整装上阵",
"热腾腾的",
"这不是铁镐么",
"抱歉，今天不行",
"冰桶挑战",
"钻石！",
"我们需要再深入些",
"用钻石包裹我",
"附魔师",
"僵尸科医生",
"隔墙有眼",
"结束了？",
"下界",
"子空间泡泡",
"可怕的要塞",
"见鬼去吧",
"与火共舞",
"诡异又可怕的骷髅",
"不稳定的同盟",
"本地的酿造厂",
"凋零山庄",
"带信标回家",
"为什么会变成这样呢？",
"信标工程师",
"末地",
"解放末地",
"下一世代",
"远程折跃",
"结束了…再一次…",
"你需要来点薄荷糖",
"在游戏尽头的城市",
"天空即为极限",
"这上面的风景不错",
"冒险",
"怪物猎人",
"这交易不错！",
"甜蜜的梦",
"瞄准目标",
"怪物狩猎完成",
"超越生死",
"招募援兵",
"探索的时光",
"狙击手间的对决",
"农牧业",
"我从哪儿来？",
"永恒的伙伴",
"开荒垦地",
"成双成对",
"均衡饮食",
"终极奉献"
    }

    ' 战利品表
    ' 来自 minecraft wiki http://minecraft-zh.gamepedia.com/%E6%88%98%E5%88%A9%E5%93%81%E8%A1%A8
    Public EnLootTables As String() = {
"minecraft:chests/abandoned_mineshaft",
"minecraft:chests/desert_pyramid",
"minecraft:chests/end_city_treasure",
"minecraft:chests/igloo_chest",
"minecraft:chests/jungle_temple",
"minecraft:chests/nether_bridge",
"minecraft:chests/simple_dungeon",
"minecraft:chests/spawn_bonus_chest",
"minecraft:chests/stronghold_corridor",
"minecraft:chests/stronghold_crossing",
"minecraft:chests/stronghold_library",
"minecraft:chests/village_blacksmith",
"minecraft:entities/sheep/black",
"minecraft:entities/sheep/blue",
"minecraft:entities/sheep/brown",
"minecraft:entities/sheep/cyan",
"minecraft:entities/sheep/gray",
"minecraft:entities/sheep/green",
"minecraft:entities/sheep/light_blue",
"minecraft:entities/sheep/lime",
"minecraft:entities/sheep/magenta",
"minecraft:entities/sheep/orange",
"minecraft:entities/sheep/pink",
"minecraft:entities/sheep/purple",
"minecraft:entities/sheep/red",
"minecraft:entities/sheep/silver",
"minecraft:entities/sheep/white",
"minecraft:entities/sheep/yellow",
"minecraft:entities/bat",
"minecraft:entities/blaze",
"minecraft:entities/cave_spider",
"minecraft:entities/chicken",
"minecraft:entities/cow",
"minecraft:entities/creeper",
"minecraft:entities/elder_guardian",
"minecraft:entities/enderman",
"minecraft:entities/endermite",
"minecraft:entities/ghast",
"minecraft:entities/giant",
"minecraft:entities/guardian",
"minecraft:entities/horse",
"minecraft:entities/magma_cube",
"minecraft:entities/mushroom_cow",
"minecraft:entities/ocelot",
"minecraft:entities/pig",
"minecraft:entities/rabbit",
"minecraft:entities/sheep",
"minecraft:entities/shulker",
"minecraft:entities/silverfish",
"minecraft:entities/skeleton",
"minecraft:entities/skeleton_horse",
"minecraft:entities/slime",
"minecraft:entities/snowman",
"minecraft:entities/spider",
"minecraft:entities/squid",
"minecraft:entities/wolf",
"minecraft:entities/zombie",
"minecraft:entities/zombie_horse",
"minecraft:entities/zombie_pigman",
"minecraft:gameplay/fishing/fish",
"minecraft:gameplay/fishing/junk",
"minecraft:gameplay/fishing/treasure",
"minecraft:gameplay/fishing",
"minecraft:empty"
    }
    Public ZhLootTables As String() = {
"废弃矿井中找到的运输矿车",
"沙漠神殿的宝藏室里的箱子",
"末地城里的箱子",
"雪屋地下室里的箱子",
"丛林神庙里的箱子",
"下界要塞里的箱子",
"地牢里的箱子",
"如果打开奖励箱选项的话，新世界生成时的奖励箱",
"要塞台阶祭坛里的箱子",
"要塞储存室里的箱子",
"要塞图书馆里的箱子",
"村庄中的铁匠铺里的箱子",
"黑色羊",
"蓝色羊",
"棕色羊",
"青色羊",
"灰色羊",
"绿色羊",
"淡蓝色羊",
"黄绿色羊",
"品红色羊",
"橙色羊",
"粉色羊",
"紫色羊",
"红色羊",
"银色羊",
"淡灰羊",
"黄色羊",
"蝙蝠",
"烈焰人",
"洞穴蜘蛛",
"鸡",
"牛",
"爬行者",
"远古守卫者",
"末影人",
"末影螨",
"恶魂",
"巨人",
"守卫者",
"马",
"岩浆怪",
"哞菇",
"豹猫",
"猪",
"兔子",
"没毛的羊",
"潜影贝",
"蠹虫",
"骷髅",
"骷髅马",
"史莱姆",
"雪傀儡",
"蜘蛛",
"墨鱼",
"狼",
"僵尸",
"僵尸马",
"僵尸猪人",
"钓上来的鱼",
"钓上来的垃圾",
"钓上来的宝物",
"钓鱼随机",
"空"
    }

    ' Json文本颜色
    ' 来自 minecraft wiki http://minecraft-zh.gamepedia.com/%E5%91%BD%E4%BB%A4#.E5.8E.9F.E5.A7.8BJSON.E6.96.87.E6.9C.AC
    Public EnJsonColors As String() = {
"white",
"black",
"gold",
"yelow",
"aqua",
"dark_aqua",
"blue",
"dark_blue",
"green",
"dark_green",
"red",
"dark_red",
"light_purple",
"dark_purple",
"gray",
"dark_gray"
    }
    Public ZhJsonColors As String() = {
"白色",
"黑色",
"金色",
"黄色",
"浅湖蓝色",
"深湖蓝色",
"浅蓝色",
"深蓝色",
"浅绿色",
"深绿色“,
"亮红色",
"深红色",
"亮紫色",
"深紫色",
"浅灰色",
"深灰色"
    }

    ' 结构名称
    ' 来自 minecraft wiki http://minecraft-zh.gamepedia.com/%E8%BF%9B%E5%BA%A6#minecraft:location
    Public EnFeatures As String() = {
"EndCity",
"Fortress",
"Mansion",
"MineShaft",
"Monument",
"Stronghold",
"Temple",
"Village"
    }
    Public ZhFeatures As String() = {
"末地城",
"下界要塞",
"林地府邸",
"废弃矿井",
"海底遗迹",
"要塞",
"神庙",
"村庄"
    }

    ' 生物群系
    ' 来自 minecraft wiki http://minecraft-zh.gamepedia.com/%E7%94%9F%E7%89%A9%E7%BE%A4%E7%B3%BB
    Public EnBiomes As String() = {
"ocean",
"plains",
"desert",
"extreme_hills",
"forest",
"taiga",
"swampland",
"river",
"hell",
"sky",
"frozen_ocean",
"frozen_river",
"ice_flats",
"ice_mountains",
"mushroom_island",
"mushroom_island_shore",
"beaches",
"desert_hills",
"forest_hills",
"taiga_hills",
"smaller_extreme_hills",
"jungle",
"jungle_hills",
"jungle_edge",
"deep_ocean",
"stone_beach",
"cold_beach",
"birch_forest",
"birch_forest_hills",
"roofed_forest",
"taiga_cold",
"taiga_cold_hills",
"redwood_taiga",
"redwood_taiga_hills",
"extreme_hills_with_trees",
"savanna",
"savanna_rock",
"mesa",
"mesa_rock",
"mesa_clear_rock",
"void",
"mutated_plains",
"mutated_desert",
"mutated_extreme_hills",
"mutated_forest",
"mutated_taiga",
"mutated_swampland",
"mutated_ice_flats",
"mutated_jungle",
"mutated_jungle_edge",
"mutated_birch_forest",
"mutated_birch_forest_hills",
"mutated_roofed_forest",
"mutated_taiga_cold",
"mutated_redwood_taiga",
"mutated_redwood_taiga_hills",
"mutated_extreme_hills_with_trees",
"mutated_savanna",
"mutated_savanna_rock",
"mutated_mesa",
"mutated_mesa_rock",
"mutated_mesa_clear_rock"
    }
    Public ZhBiomes As String() = {
"海洋",
"草原",
"沙漠",
"峭壁",
"森林",
"针叶林",
"沼泽",
"河流",
"地狱(下界)",
"末路之地(空岛)",
"冻洋",
"冻河",
"冰原",
"雪山",
"蘑菇岛",
"蘑菇岛岸",
"沙滩",
"沙漠山丘",
"森林山丘",
"针叶林山丘",
"悬崖",
"丛林",
"丛林山丘",
"丛林边缘",
"深海",
"石滩",
"寒冷沙滩",
"桦木森林",
"桦木森林山丘",
"黑森林",
"冷针叶林",
"冷针叶林山丘",
"大型针叶林",
"大型针叶林山丘",
"峭壁+",
"热带草原",
"热带高原",
"平顶山",
"平顶山高原F",
"平顶山高原",
"虚空",
"向日葵草原",
"沙漠M",
"峭壁M",
"繁花森林",
"针叶林M",
"沼泽M",
"冰刺平原",
"丛林M",
"丛林边缘M",
"桦木森林M",
"桦木森林山丘M",
"黑森林M",
"冷针叶林M",
"红木森林",
"红木山丘",
"峭壁+M",
"热带草原M",
"热带高原M",
"平顶山(岩柱)",
"平顶山高原FM",
"平顶山高原M"
    }
End Module